### PR TITLE
ssl: drop RAND_status() checks

### PR DESCRIPTION
**Pull request by flatcap**
`RAND_status()` was added to OpenSSL 20 years ago.

https://github.com/openssl/openssl/blame/54a0d4ceb28d53f5b00a27fc5ca8ff8f0ddf9036/include/openssl/rand.h#L62

### CODE REVIEW

**Comment by flatcap** [comment]
> `DEV_RANDOM`

It was used in the `else` clause of the macro.
https://github.com/neomutt/neomutt/pull/2073/files#diff-ce1d6e16ac66f7b7485531cde2340711L105

> If so, how did you discover this?

... though I _do_ occasionally `grep -c` on all the `#define`s

**Comment by flatcap** [comment]
btw, the CODEOWNERS didn't trigger the reviewers.
I'm not sure if it's because **I** match the owner regex, or because I'm an admin.

**Comment by Austin-Ray** [comment]
@flatcap: I wonder if we need to enable the require review and require code owners to auto add them. I think I may have misinterpreted the `CODEOWNERS` documentation

**Comment by flatcap** [comment]
> enable the require review and require code owners to auto add them

OK, let's give that a go.  I've enabled the option.

**Pull request merged**
