### PR TITLE
Pull request for devel/sileht-fix-postponed-big

### LINKED ISSUE #1425: Postponed mail are opened only on second try
## Expected Behaviour

Open postponed mail on first try

## Actual Behaviour

My postponed message is opened only on second try

## Steps to Reproduce

On imap, when I have postponed mail and I create a new mail:

I press `m` (<mail>), I got `Recall postponed message? ([yes]/no):`
I press `y` -> I got `No postponed messages`
I press `m` -> I got `Recall postponed message? ([yes]/no):`
I press `y` -> I got my postponed message opened

## How often does this happen?

- Always

## NeoMutt Version

20180716-749-3728e4

### PR DESCRIPTION
**Pull request by sileht**
imap: make imap_mbox_open reentrant once.
imap: split imap_mbox_open code

Edit @gahr - I took the liberty to copy the explanation from the second commit:

While we have opened a mailbox, we press 'm' to callback a postponed
message. Neomutt open a view with all postponed messages (with
imap_mbox_open without APPEND flag).

This changes the current select folder on imap server and neomutt never
select back the original folder, letting neomutt into a weird state.

this change update imap_mobx_open/close to become reentrant once to
support the postponed messages use case.

Now when we close the postponed mailbox, we select back the previous
opened mailbox.

Closes #1425

### CODE REVIEW

**Comment by gahr** [comment]
I'm seeing something weird:

go to your `postponed` mailbox, make sure you have a couple of drafts there. Press `m`, you get the error `No postponed messages` and are left with the index in an empty `postponed` mailbox (in my case the status bar is `---NeoMutt: +Drafts [Msgs:0 0]`).

**Comment by sileht** [comment]
@gahr I proposed https://github.com/neomutt/neomutt/pull/1444 for your issue.

**Comment by sileht** [comment]
I fixed the crash.

**Comment by sileht** [comment]
I don't think it's needed anymore.

**Pull request closed without merging**
