### PR TITLE
check for new mail while in pager when idle

### PR DESCRIPTION
**Pull request by sassmann**
Currently, when the pager is open and mutt is idle the mailboxes aren't
checked for new mails. Change the behaviour to get notified of newly
arrived mail.
Note: Removed the huge if clause that exists to filter out the currently
selected folder. Not seeing any reason why this check is necessary in
the first place.

Signed-off-by: Stefan Assmann <sassmann@kpanic.de>

### CODE REVIEW

**Comment by flatcap** [comment]
Hi @sassmann1 this sounds good.
However, the build failed -- [build log](https://travis-ci.org/neomutt/neomutt/builds/151737213)
I presume it worked for you?

**Comment by sassmann1** [comment]
Hi flatcap, yes I did work for me. I'll look into it!

**Comment by flatcap** [comment]
If things "look right" to you don't worry about it.
Travis has been having some random build failures (I did try yours twice).

**Comment by sassmann1** [comment]
I see the problem, the build system uses different configure options
  GPGME:             yes
  PGP:               yes
  SMIME:             yes
  Sidebar:           no
  Notmuch:           no
while I enabled sidebar and notmuch in my testing. So I was able to reproduce that. Going to make the changes so it builds correctly. I'll close this request and get out a new one once it's fixed. Is that ok?

**Comment by flatcap** [comment]
Yes, Travis is configure to do two builds -- one with everything enable, one with everything disabled.
No need to close and reopen.  You can commit to this pull-request, fixing it.
When everything's fixed, I can squash the commits into one "beautiful" commit and merge that.

**Comment by flatcap** [comment]
Thanks.  I'll have a good look at this later.

**Comment by sassmann1** [comment]
All good now! Btw neomutt is awesome, keep up the good work.

**Comment by sassmann** [comment]
I just noticed that you reported this as issue #19

**Comment by sassmann** [comment]
flatcap, you haven't merged this yet. Anything I can do to help?

**Comment by flatcap** [comment]
hi @sassmann 
Sorry for the delay in service.
I've been a bit busy with the new release.
I've been a bit lazy.

I looked at the patch, at the time and it looked good, but it's changing a critical part of Mutt, so I needed to be sure.  Also, a couple of NNTP lines seemed to vanish.  Maybe a typo, but I didn't have time to check.

I've ported it forward to the new Mutt.  I'll make an effort to get it merge ASAP.

**Comment by flatcap** [comment]
Hi @sassmann 

Thanks, I've merged your change to `pager.c`
However, I left out the change to `buffy.c`

> Note: Removed the huge if clause that exists to filter out the currently
> selected folder. Not seeing any reason why this check is necessary in
> the first place.

Hmm... I stared at this bit of code long and hard.
I don't understand it either, but:
- It's been there a **long** time
- The change isn't necessary to make the pager check for new mail

I suggest asking on the Mutt Dev mailing list: mutt-dev@mutt.org

**Pull request closed without merging**
