### PR TITLE
Don't indent named mailboxes with %D

### PR DESCRIPTION
**Pull request by nabijaczleweli**
* **What does this PR do?**

Supersede #2585

* **What are the relevant issue numbers?**

https://github.com/neomutt/neomutt/pull/2585#issuecomment-675326474

### CODE REVIEW

**Comment by gahr** [comment]
I think it's wrong to disable indentation for named mailboxes. Here's why:

Using

```
set sidebar_format="%?N?%5N&     ?│%5S│%D%* %?F? !%F ?%?t? *%t?"
```

These mailboxes

```
+FreeBSD
+FreeBSD.@arch
```

are displayed in the sidebar like this

```
     │34858│FreeBSD
  153│  494│··@arch
```

Using

```
named-mailboxes "Arch stuff" +FreeBSD.@arch
```

I get

```
     │34858│FreeBSD
  153│  494│Arch stuff
```

while I would like to get

```
     │34858│FreeBSD
  153│  494│··Arch stuff
```

Can you please explain what is **your** rationale for wanting this change?

**Comment by nabijaczleweli** [comment]
it fixes this:
screenshot

I would've preferred #2585 which'd make this consistent, and you [said](https://github.com/neomutt/neomutt/pull/2585#issuecomment-675326474) you didn't see a reason for the approach that would let you do exactly what you described above; to get my preferred behaviour, consistent with previous versions, I called my mailboxes `"feeds"`, `"  podcasts"`, `"  webcomics"` instead of `"feeds"`, `"feeds/podcasts"`, `"feeds/webcomics"`, which looks right:
screenshot

Even if it makes the window title useless

**Comment by gahr** [comment]
Well yeah the fact that indentation is sometimes wrong (it is when your named mailboxes aren’t under `folder`) doesn’t imply it is always wrong and we should kill it altogether.

Regarding shortening: that is done based either on URL or folder. Shortening any named mailbox based on occurrences of slashes is not what it was designed to do. It would be a nice feature, but it needs to be implemented.

**Comment by nabijaczleweli** [comment]
I mean, it *was* a nice feature until it was removed, but sure.

**Comment by gahr** [comment]
Sorry, that is *not* what the other PR achieved. It might have for your particular use case, but it broke other stuff. I am sorry if you feel I turned down your PR based on mere personal taste. I have not.

**Comment by nabijaczleweli** [comment]
Oh, no, I was merely referring to the fact that this *had* worked until it didn't; calling this a would-be nice feature is hence misleading at best. I'll see about another implementation.

**Pull request closed without merging**
