### PR TITLE
Devel/issue 1180

### PR DESCRIPTION
**Pull request by nobrowser**
I think you should merge this (even though I have not begun the real part), because the work is growing with each large commit to master.

### CODE REVIEW

**Comment by mschilli87** [comment]
According to github, there are no differences between your branch and master.
I did a `git diff` on a local checkout and it has 281,210(!) lines.
This might explain why github doesn't try to show a diff.
I think to actually review this, it must be split into separate pull request.
I would start by rebasing `devel/issue-1180` on top of `master` instead of the merge.
Using `rebase -i` the commits could be split/merged into reviewable chunks and the either merged in sequence or split into *independent* branches via `git branch`/`git checkout [-b]` and `git rebase -i` which could be submitted in parallel for review/merge.
If you need any help with how to do this using command line `git`, I can help. But as I don't know the chnages, I can't do the actual `rebase -i` myself.

**Comment by flatcap** [comment]
Hmm...
Excluding the merges, this branch only contains 6 unique commits:
- a65d62b96 Factor out awful inline code for logging binary buffer
- c9510fd41 Align numeric log level arguments                 
- d717d18c2 Adjust symbolic logging levels to avoid level 4, to be PROGRESS
- df6ab1a4d Fix wrong calculation of remaining length in nntp_log_binbuf     
- a8f97527d Start replacing numeric loglevels with symbolic.
- d76a2f957 Remove extra copy of SASL helper functions   

The first 5 were merged into master 3 weeks ago (f6be12dac).
The 6th commit removed a couple of duplicate functions, but I removed the dupes from the original commits when I merged them.

I believe there's no unmerged work in this branch.

**Comment by mschilli87** [comment]
@flatcap 
> I believe there's no unmerged work in this branch

```sh
# Get a fresh clone in `/tmp`.
cd /tmp
git clone git@github.com:neomutt/neomutt.git
```

```
Cloning into 'neomutt'...
remote: Enumerating objects: 551, done.
remote: Counting objects: 100% (551/551), done.
remote: Compressing objects: 100% (358/358), done.
remote: Total 76542 (delta 317), reused 269 (delta 193), pack-reused 75991
Receiving objects: 100% (76542/76542), 75.55 MiB | 667.00 KiB/s, done.
Resolving deltas: 100% (61610/61610), done.
Checking connectivity... done.
```

```sh
# Enter fresh clone.
cd neomutt

# Checkout source branch of the PR.
git checkout devel/issue-1180
```
```
Branch devel/issue-1180 set up to track remote branch devel/issue-1180 from origin.
Switched to a new branch 'devel/issue-1180'
```

```sh
# Compare to target branch of the PR.
git diff master | wc -l
```

```
281210
```

If all changes where merged, the diff should be empty.

```sh
# Check first few lines of diff.
git diff master | head -n 50
```

```
diff --git a/Makefile.autosetup b/Makefile.autosetup
index 6c5baac..0c5e7e7 100644
--- a/Makefile.autosetup
+++ b/Makefile.autosetup
@@ -237,7 +237,7 @@ ALLOBJS+=   $(LIBCONFIGOBJS)
 # libemail
 LIBEMAIL=      libemail.a
 LIBEMAILOBJS=  email/address.o email/attach.o email/body.o \
-               email/email_globals.o email/envelope.o email/from.o email/group.o \
+               email/email_globals.o email/envelope.o email/from.o \
                email/email.o email/idna.o email/mime.o email/parameter.o \
                email/parse.o email/rfc2047.o email/rfc2231.o email/tags.o \
                email/thread.o email/url.o
@@ -249,7 +249,7 @@ ALLOBJS+=   $(LIBEMAILOBJS)
 # libmutt
 LIBMUTT=       libmutt.a
 LIBMUTTOBJS=   mutt/base64.o mutt/buffer.o mutt/charset.o mutt/date.o \
-               mutt/envlist.o mutt/exit.o mutt/file.o mutt/hash.o \
+               mutt/envlist.o mutt/exit.o mutt/file.o mutt/group.o mutt/hash.o \
                mutt/history.o mutt/list.o mutt/logging.o mutt/mapping.o \
                mutt/mbyte.o mutt/md5.o mutt/memory.o mutt/path.o mutt/regex.o \
                mutt/sha1.o mutt/signal.o mutt/string.o
diff --git a/addrbook.c b/addrbook.c
index ee961f4..849792d 100644
--- a/addrbook.c
+++ b/addrbook.c
@@ -46,10 +46,10 @@
 #include "sort.h"

 /* These Config Variables are only used in addrbook.c */
-char *C_AliasFormat; ///< Config: printf-like format string for the alias menu
-short C_SortAlias;   ///< Config: Sort method for the alias menu
+char *AliasFormat; ///< Config: printf-like format string for the alias menu
+short SortAlias;   ///< Config: Sort method for the alias menu

-#define RSORT(num) ((C_SortAlias & SORT_REVERSE) ? -num : num)
+#define RSORT(x) ((SortAlias & SORT_REVERSE) ? -x : x)

 static const struct Mapping AliasHelp[] = {
   { N_("Exit"), OP_EXIT },      { N_("Del"), OP_DELETE },
@@ -71,9 +71,9 @@ static const struct Mapping AliasHelp[] = {
 static const char *alias_format_str(char *buf, size_t buflen, size_t col, int cols,
                                     char op, const char *src, const char *prec,
                                     const char *if_str, const char *else_str,
-                                    unsigned long data, MuttFormatFlags flags)
+                                    unsigned long data, enum FormatFlag flags)
 {
-  char fmt[128], addr[128];
+  char fmt[SHORT_STRING], addr[SHORT_STRING];
   struct Alias *alias = (struct Alias *) data;
```

```sh
# Start an interactive rebase (to get rif of merge(d) commits and).
git rebase -i master
```

```
pick a65d62b Factor out awful inline code for logging binary buffer
pick c9510fd Align numeric log level arguments
pick d717d18 Adjust symbolic logging levels to avoid level 4, to be PROGRESS
pick df6ab1a Fix wrong calculation of remaining length in nntp_log_binbuf
pick a8f9752 Start replacing numeric loglevels with symbolic.
pick b263f9a Factor out awful inline code for logging binary buffer
pick 7d7bd61 Align numeric log level arguments
pick 4ee4e65 Adjust symbolic logging levels to avoid level 4, to be PROGRESS
pick a6a28c1 Fix wrong calculation of remaining length in nntp_log_binbuf
pick 639f6c4 Start replacing numeric loglevels with symbolic.
pick d76a2f9 Remove extra copy of SASL helper functions

# Rebase d50a681..c04376c onto d50a681 (11 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

Comparing this to your list

> * a65d62b Factor out awful inline code for logging binary buffer
> * c9510fd Align numeric log level arguments
> * d717d18 Adjust symbolic logging levels to avoid level 4, to be PROGRESS
> * df6ab1a Fix wrong calculation of remaining length in nntp_log_binbuf
> * a8f9752 Start replacing numeric loglevels with symbolic.
> * d76a2f9 Remove extra copy of SASL helper functions


leaves

* b263f9a Factor out awful inline code for logging binary buffer
* 7d7bd61 Align numeric log level arguments
* 4ee4e65 Adjust symbolic logging levels to avoid level 4, to be PROGRESS
* a6a28c1 Fix wrong calculation of remaining length in nntp_log_binbuf
* 639f6c4 Start replacing numeric loglevels with symbolic.

which seems to simply apply the same changes again on top.

So I adjusted the `rebase` task list to

```
pick a65d62b Factor out awful inline code for logging binary buffer
fixup b263f9a Factor out awful inline code for logging binary buffer
pick c9510fd Align numeric log level arguments
fixup 7d7bd61 Align numeric log level arguments
pick d717d18 Adjust symbolic logging levels to avoid level 4, to be PROGRESS
fixup 4ee4e65 Adjust symbolic logging levels to avoid level 4, to be PROGRESS
pick df6ab1a Fix wrong calculation of remaining length in nntp_log_binbuf
fixup a6a28c1 Fix wrong calculation of remaining length in nntp_log_binbuf
pick a8f9752 Start replacing numeric loglevels with symbolic.
fixup 639f6c4 Start replacing numeric loglevels with symbolic.
pick d76a2f9 Remove extra copy of SASL helper functions
```

to ensure no changes are lost during the rebase (I didn't want to blindly assume that two commit with the same commit message also have identical changes).


Going ahead with the rebase I got

```
error: could not apply a65d62b... Factor out awful inline code for logging binary buffer

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply a65d62b96720ff00e83d1b9f38202767c35001cb... Factor out awful inline code for logging binary buffer
```

and a quick

```sh
git status
```

showed

```
interactive rebase in progress; onto d50a681
Last command done (1 command done):
   pick a65d62b Factor out awful inline code for logging binary buffer
Next commands to do (10 remaining commands):
   fixup b263f9a Factor out awful inline code for logging binary buffer
   pick c9510fd Align numeric log level arguments
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'devel/issue-1180' on 'd50a681'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   nntp/nntp.c

no changes added to commit (use "git add" and/or "git commit -a")

```

Investigation `nntp/nntp.c`, the changes look different but the same:

```
<<<<<<< HEAD
            if (*buf != '\0')
=======
            if (*buf)
>>>>>>> a65d62b... Factor out awful inline code for logging binary buffer

```

```
<<<<<<< HEAD
          else
=======
          else 
>>>>>>> a65d62b... Factor out awful inline code for logging binary buffer
```

(The second else has an extra space in the end!)

I would keep the `HEAD` version for both of them (and If I didn't mix things up, that's how it should be in master already).

```sh
# Continue the rebase.
git add nntp/nntp.c && git rebase --continue
```

```
[detached HEAD f8ac627] Factor out awful inline code for logging binary buffer
 Author: Ian Zimmerman <itz@no-use.mooo.com>
 1 file changed, 30 insertions(+)
error: could not apply b263f9a... Factor out awful inline code for logging binary buffer

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply b263f9a3cf1a28e21e0cdae5310078451c374c02... Factor out awful inline code for logging binary buffer
```

This time the differences where bigger:

```
<<<<<<< HEAD
 * nntp_memchr - look for a char in a binary buf, conveniently
 * @param haystack [in/out] input: start here, output: store address of hit
 * @param sentinel points just beyond (1 byte after) search area
 * @param needle the character to search for
 * @retval true found and updated haystack
 * @retval false not found
 */
static bool nntp_memchr(char **haystack, char *sentinel, int needle)
{
  char *start = *haystack;
  size_t max_offset = sentinel - start;
  void *vp = memchr(start, max_offset, needle);
  if (!vp)
    return false;
  *haystack = vp;
  return true;
}

/**
 * nntp_log_binbuf - log a buffer possibly containing NUL bytes
 * @param buf source buffer
 * @param len how many bytes from buf
 * @param pfx logging prefix (protocol etc.)
 * @param dbg which loglevel does message belong
 */
static void nntp_log_binbuf(const char *buf, size_t len, const char *pfx, int dbg)
{
  char tmp[1024];
  char *p = tmp;
  char *sentinel = tmp + len;

  if (C_DebugLevel < dbg)
    return;
  memcpy(tmp, buf, len);
  tmp[len] = '\0';
  while (nntp_memchr(&p, sentinel, '\0'))
    *p = '.';
  mutt_debug(dbg, "%s> %s\n", pfx, tmp);
}
#endif

/**
=======
>>>>>>> b263f9a... Factor out awful inline code for logging binary buffer
```

```
<<<<<<< HEAD
=======
#endif
>>>>>>> b263f9a... Factor out awful inline code for logging binary buffer
```

```
<<<<<<< HEAD
            if (*buf != '\0')
=======
            if (*buf)
>>>>>>> b263f9a... Factor out awful inline code for logging binary buffer
```

But again, the `HEAD` (*i.e.* `master` version is probably what we want).

```sh
# Continue the rebase.
git add nntp/nntp.c && git rebase --continue
```

```
error: could not apply c9510fd... Align numeric log level arguments

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply c9510fd41dea890cd9e8e52bd8955449a938bc35... Align numeric log level arguments
```

```sh
git status
```

```
interactive rebase in progress; onto d50a681
Last commands done (3 commands done):
   fixup b263f9a Factor out awful inline code for logging binary buffer
   pick c9510fd Align numeric log level arguments
  (see more in file .git/rebase-merge/done)
Next commands to do (8 remaining commands):
   fixup 7d7bd61 Align numeric log level arguments
   pick d717d18 Adjust symbolic logging levels to avoid level 4, to be PROGRESS
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'devel/issue-1180' on 'd50a681'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   browser.c
        both modified:   imap/command.c
        both modified:   imap/util.c
        both modified:   index.c
        both modified:   init.c
        both modified:   maildir/shared.c
        both modified:   monitor.c
        both modified:   mutt_parse.c
        both modified:   ncrypt/crypt_gpgme.c
        both modified:   ncrypt/gnupgparse.c
        both modified:   ncrypt/pgp.c
        both modified:   ncrypt/pgpkey.c
        both modified:   nntp/newsrc.c
        both modified:   rfc3676.c
        both modified:   sendlib.c

no changes added to commit (use "git add" and/or "git commit -a"
```

Add this stage, the difference just got too many for me to review right now.

```sh
# Undo rebase so far.
git rebase --abort

# Leave fresh clone.
cd ..

# Cleanup fresh clone.
rm -rf neomutt
```

But I'm afraid without anyone actually going through the *whole* rebase, there is no way to tell if this PR has any changes that should be merged.

**Comment by mschilli87** [comment]
@flatcap: Thx for taking the time to explain. It makes sense now to me. I guess I did not see this as clearly in my rebase attempt as I also modified the commit order. So I would have probably manually resolved differences that would have come anyway in a later commit. I think at this point we can trust you to do the right thing. :wink:

Regarding the complications factors, IIRC this was the main arguments against your refactoring/cleanup/cosmetic changes in the mutt mailing list.
Seeing where your (not only but particularly) work since the creation of neomutt has led so far, I'd say situtation like these are easily worth the gains. :smile:

**Comment by nobrowser** [comment]
Ok, let's delete the branch now, and I'll fork off a new one.  I got discouraged trying to rebase, exactly as @mschilli87 did above.

**Comment by flatcap** [comment]
No action required

**Pull request closed without merging**
