### PR TITLE
Internationalize strings

### PR DESCRIPTION
**Pull request by Alok**
This is a *very* crude effort that's nothing more than 2 `vim` macros
combined with `ag`. It is split into a few separate commits to make
reverting easier. Feel free to ignore the whole thing since I don't
actually know any C, or how `gettext`'s `_` works.

### CODE REVIEW

**Comment by Alok** [comment]
Is meant to address #233 .

**Comment by flatcap** [comment]
Hi @Alok,

Thanks for this...

> Feel free to ignore the whole thing since I don't actually know any C

Ah, this could be a very interesting pull-request.

> Commit 1 - remove some spaces

That's fine.

> Commit 2 - Parenthesise all `_()` uses

This is a bit trickier.  `_` is a valid C function name (it's `#define`d so `_()` becomes `gettext()`.
So...
This change isn't needed
```diff
-  menu->title = _("Aliases");
+  menu->title = (_("Aliases"));  
```

But this one **is** (due to a widespread mistake in mutt):
```diff
-    mutt_error _("You have no aliases!");
+    mutt_error (_("You have no aliases!"));  
```

> Commit 3 - widespread wrapping of strings

Hmm...
The purpose of gettext is to mark strings that need to be translated.  In any given program, there will be lots of strings that shouldn't be translated:
- Contain only whitespace: `\n`
- Names of environment variables: `TERM`
- Standard email headers: `To:`, `Subject:`
- Function names
- File names
- Comments in the code (your macro is too powerful :-)

It'll take a little while to sort out -- I'll wait 'til there's something undemanding on TV.
Thanks.

**Comment by Alok** [comment]
This is what happens when you indiscriminately run a macro 1376 times in Vim =(.

**Comment by flatcap** [comment]
This PR is superceded by #376

**Pull request closed without merging**
