### PR TITLE
Add bool browser_sort_dirs_first, always putting directories first

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Closes: #3948

partition-alpha:

### CODE REVIEW

**Comment by flatcap** [comment]
Thanks for the PR.  I'll have a look in the morning.

I've merged your `.gitignore` fix, with one small tweak.
I altered `Makefile.autosetup` to correctly delete `jimsh0` on `make distclean`.

I tried to rebase the PR over main, but it wouldn't let me:
```
To github.com:nabijaczleweli/neomutt
 ! [remote rejected]     sort_browser-partition -> sort_browser-partition (permission denied)
error: failed to push some refs to 'github.com:nabijaczleweli/neomutt'
```

Did you untick the box marked "Allow administrators to make updates"?

**Comment by nabijaczleweli** [comment]
It's not ticked by default anymore for me, but yes; rebased.

**Review by flatcap — CHANGES_REQUESTED** [review]
I like the idea, but not the implementation.  Sorry :-)

The `partition-` flag doesn't really fit in.
`reverse-` has _meaning_ for all of file/directories/mailboxes, but `partition-` doesn't.

Please can we go back to a separate config variable.
As it's very specific, how about: `browser_sort_dirs_first`?

Thanks!

**Comment by nabijaczleweli** [comment]
And it's much simpler to boot.

**Comment by flatcap** [comment]
That looks good.
I've made a few light tweaks, but I can't push them.

**Comment by flatcap** [comment]
**tidy**
- clang-format
- tidy doc descriptions
- check for config change

**sort**
- Alter `browser_config_observer()`, so that changes to `$browser_sort_dirs_first` updates the display

**Comment by nabijaczleweli** [comment]
Yep, works for me

**Review by flatcap — APPROVED** [review]
Lovely.  Thanks!

**Pull request merged**
