### PR TITLE
configure: remove MUTTLIBS

### PR DESCRIPTION
**Pull request by d-k-c**
* **What does this PR do?**

Remove MUTTLIBS from autotools

* **Are there points in the code the reviewer needs to double check?**

Does it sill configure and build in your environment? Do you have link issues? Make sure all found and required libraries are indeed assigned to LIBS.

* **What are the relevant issue numbers?**

See issue #552

### CODE REVIEW

**Comment by flatcap** [comment]
My BIG test script shows that it's only the `--with-ssl` build that fails.

**Comment by gahr** [comment]
```diff
diff --git a/configure.ac b/configure.ac
index d7cb37b7..e29f657d 100644
--- a/configure.ac
+++ b/configure.ac
@@ -514,7 +514,7 @@ AC_ARG_WITH(ssl, AS_HELP_STRING([--with-ssl@<:@=PFX@:>@],[Enable TLS support usi
                AC_CHECK_LIB(ssl, SSL_new,,
                        AC_MSG_ERROR([Unable to find SSL library]), [$crypto_libs])

-               LIBS="$saved_LIBS $crypto_libs"
+               LIBS="$saved_LIBS -lssl $crypto_libs"
                AC_CHECK_FUNCS(RAND_status RAND_egd)
                AC_CHECK_DECLS([SSL_set_mode, SSL_MODE_AUTO_RETRY],,
                        AC_MSG_ERROR([Unable to find decent SSL header]), [[#include <openssl/ssl.h>]])
```
This fixes the issue with `--with-ssl` for me.

**Comment by d-k-c** [comment]
That makes sense, `-lssl` was appended to `MUTTLIBS` but for some reasons I dropped that. Just pushed a fixup version with your suggestion @gahr

**Comment by flatcap** [comment]
Merged

**Pull request closed without merging**
