### PR TITLE
Added waffle links to README

### PR DESCRIPTION
**Pull request by guyzmo**

### CODE REVIEW

**Comment by toogley** [comment]
LGTM. 

Maybe should also add a graph like below?

[Throughput Graph](https://waffle.io/neomutt/neomutt/metrics/throughput)

**Comment by guyzmo** [comment]
I'm not against. But it's not necessary to overload the readme with information… even more as the readme is stuffed under 6 pages of file listing!

**Comment by toogley** [comment]
@guyzmo yep. But given that the history of mutt development was rather unfriendly at certain times, this graph may provide additional evidence that we're active. Therefore i think its not unnecessary.

**Comment by guyzmo** [comment]
Maybe then on the neomutt.org website?

**Comment by toogley** [comment]
@guyzmo its of course an option, but i don't know which one is better.

**Comment by flatcap** [comment]
I've added the badges to the README as they're quite modest.
And, I've added the badges and graph to the [devel webpage](https://www.neomutt.org/dev.html).

**Pull request closed without merging**
