### PR TITLE
Devel/issue 1180

### PR DESCRIPTION
**Pull request by nobrowser**
Hi, please merge this so I can avoid continuous and labor-intensive rebasing.  It changes nothing else than change `mutt_debug([1-3], ...)` to `mutt_debug(LL_DEBUG[1-3], ...)` .  Thanks.

### CODE REVIEW

**Comment by nobrowser** [comment]
Looks like the merge dropped the part of my changes where the function is used, and that's why the compilation failed.  I don't know why the merge would do that.  I concede defeat to git (or is it github?)

:-(

I guess I can try to merge locally and see what happens.  Will report on that.

**Comment by flatcap** [comment]
> so I can avoid continuous and labor-intensive rebasing

Don't worry about trying to keep up with my sporadic cleaning frenzies.
I offer a free rebase service for all pull-requests -- you only need ask.

>  I don't know why the merge would do that. I concede defeat to git

git rebase and merge are pretty amazing, but there are limits.
Situations where there are widespread changes on both branches will always be tricky.

Fortunately, I've had a **lot** of experience rebasing patches,
plus I have a good handle on the changes I've made.

I have a copy of your branch **pre**-rebase.   I'll start there.
If things go smoothly, I'll push the results back here (in a few hours, maybe).
If not, I'll have another go in the morning.

**Comment by flatcap** [comment]
After writing all that, your merge was fine :-)
The Travis build uses `-Werror` to fail on warnings.
You just needed `#ifdef USE_SASL` around `nntp_memchr()` and `nntp_log_binbuf()`.

Oh, and I accidentally deleted your branch, closing this issue.  Sorry.

**Comment by nobrowser** [comment]
> You just needed `#ifdef USE_SASL` around `nntp_memchr()` and `nntp_log_binbuf()`.

Bingo.  Thanks.

I'll push my branch again if needed.

**Comment by flatcap** [comment]
> I'll push my branch again if needed.

No need, I've reinstated it and opened #1570

**Pull request closed without merging**
