### PR TITLE
Document that $sort_alias affects the query menu

### PR DESCRIPTION
**Pull request by ftilde**
* **What does this PR do?**
Document (in manual and man page) the fact that the alias and query menu are now identical and that consequently `$sort_alias` also affects the query menu.

* **What are the relevant issue numbers?**
#2692

### CODE REVIEW

**Review by flatcap — APPROVED** [review]
I just tweaked your change to put it in `<note>` tags.
Thanks

**Comment by flatcap** [comment]
btw, which is your preferred address: "tamepointer" or "protonmail"?

**Comment by ftilde** [comment]
On 13.10.2020 05:02, Richard Russon wrote:
>I just tweaked your change to put it in `<note>` tags.
That makes sense. Thanks!

**Comment by ftilde** [comment]
On 13.10.2020 05:08, Richard Russon wrote:
>btw, which is your preferred address: "tamepointer" or "protonmail"?
tamepointer. I've recently(ish) moved away from protonmail because of 
the annoying smpt/imap situation.

**Pull request merged**
