### PR TITLE
Update zh_CN translation

### PR DESCRIPTION
**Pull request by l2dy**
* **What does this PR do?**
@yuzibo "个" is needed here.

* **What are the relevant issue numbers?**

### CODE REVIEW

**Comment by yuzibo** [comment]
Sorry for later reply.
Maybe you have known my worry about the translate.　
I just  am not clear the plural translate for here.
Do you think that there is never path to translate  "Print tagged attachment?"
If so, i am sure that the translate is no problem.
Please correct me.

**Comment by l2dy** [comment]
With `Plural-Forms: nplurals=1; plural=0;`, I don't think there's a way to omit the " 1 " without changing the code. See https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html for details.

```
snprintf(prompt, sizeof(prompt),
         /* L10N: Although we now the precise number of tagged messages, we
            do not show it to the user.  So feel free to use a "generic
            plural" as plural translation if your language has one. */
         tag ? ngettext("Print tagged attachment?", "Print %d tagged attachments?", tagmsgcount) :
               _("Print attachment?"),
         tagmsgcount);
```

Here the `ngettext` function returns `msgstr[0]` for zh_CN and snprintf takes that as the format string. snprintf discards excess arguments, but in our case we can only have one format string so we can't have one with `%d` and another without `%d`.

**Comment by yuzibo** [comment]
Ok,
Only the program run here,it tagged more than zero attachment that need %d + quantifier
You are right.
Could you have glance at line 1745&2628.

**Comment by l2dy** [comment]
@yuzibo Line 2628 already has "个" in the translation; for line 1745 see #1230.

**Comment by yuzibo** [comment]
2628..
I mean %2$s and %1$d. The '$' i don know it from where :)
BTW,if "在％S中..."　would be better?

**Comment by l2dy** [comment]
Right, see https://www.gnu.org/software/gettext/manual/html_node/c_002dformat.html, it's for reordering arguments.

No, "在" is unnecessary here.

**Comment by yuzibo** [comment]
Thanks!

**Pull request merged**
