### PR TITLE
Fix setting of DT_MAILBOX type variables from Lua

### PR DESCRIPTION
**Pull request by darnir**
* **What does this PR do?**

Checks if the given variable in Lua maps to a DT_PATH type and if so,
expands the path to replace the "+" with the value of $folder

Closes: #2008

* **Screenshots (if relevant)**

* **Does this PR meet the acceptance criteria?** (This is just a reminder for you,
  this section can be removed if you fulfill it.)

   - Documentation created/updated (you have to edit
     [doc/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/master/doc/manual.xml.head)
     for that)

Not needed

   - All builds and tests are passing

Not sure. It works fine, locally for my own configuration

   - Added [doxygen code documentation](https://neomutt.org/dev/doxygen)
     [syntax](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)

   - Code follows the [style guide](https://neomutt.org/dev/coding-style)

Yes

* **What are the relevant issue numbers?**

### CODE REVIEW

**Comment by darnir** [comment]
According to https://www.lua.org/pil/24.2.2.html the API is `lua_strlen` and it works on my Fedora 31 system as well. I wonder what version of Lua is available on travis that it refuses this API

**Comment by flatcap** [comment]
Travis is running Ubuntu 18.04.
Ah, we're installing `liblua5.2-dev`

**Comment by flatcap** [comment]
Hmm... Your guide says:

> This first edition was written for Lua 5.0.
> While still largely relevant for later versions, there are some differences.

In the header file, `lua_strlen()` is in a `#if defined(LUA_COMPAT_5_1)` block.
It seems that we want `lua_len()` -- https://www.lua.org/manual/5.3/manual.html#lua_len

**Comment by flatcap** [comment]
It turns out that my Travis' Ubuntu 18.04 needed the symbol `LUA_COMPAT_ALL` defining.
My Fedora box and later versions of Ubuntu (like LGTM), need the symbol `LUA_COMPAT_5_1` defining.

**Pull request merged**
