### PR TITLE
Add a new command purge-thread analogous to delete-thread

### PR DESCRIPTION
**Pull request by darnir**

### CODE REVIEW

**Comment by flatcap** [comment]
Hi @darnir 
I've pushed your changes into: [devel/purge-thread](https://github.com/neomutt/neomutt/tree/devel/purge-thread)

It doesn't quite work the same as `delete-thread`, though:
Given a thread:
```
1 r + Aug 20 Darshit  purge-thread
2   F Aug 21 Richard  ├─>
3 r + Aug 22 Darshit  └─>
4   + Aug 23 Darshit    ├─>
5 r F Aug 24 Richard    └─>
6   F Aug 25 Richard      ├─>
7   + Aug 26 Darshit      └─>
```

If you `<delete-thread>` on **any** of the emails, then the **whole thread** is deleted.

If you `<purge-thread>` on email:
- **1**, then **all** emails are deleted.
- **5**, then **emails 5-7** are deleted.
- **7**, then **only email 7** is deleted.

**Comment by pickfire** [comment]
@darnir Does `<purge-thread>` works the same as `<delete-subthread>`?

**Comment by darnir** [comment]
Seems like it works like delete-subthread. I'll check the code again to see
where I went wrong.

This was written in a hurry and not really well tested.

Thanking You,
Darshit Shah
Sent from mobile device. Please excuse my brevity

On 01-Sep-2016 8:07 AM, "Ivan Tham" <notifications@github.com> wrote:

@darnir <https://github.com/darnir> Does <purge-thread> works the same as
<delete-subthread>?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/neomutt/neomutt/pull/123#issuecomment-243984817>, or mute
the thread

**Comment by pickfire** [comment]
@darnir, so is this merged?

**Comment by darnir** [comment]
Fixed and merged

Thanking You,
Darshit Shah

**Pull request closed without merging**
