### PR TITLE
Finished spanish translation

### PR DESCRIPTION
**Pull request by Robdres**
* **What does this PR do?**
This PR is the finshed translation in Spanish

### CODE REVIEW

**Comment by flatcap** [comment]
> This PR is the finshed translation in Spanish

Ah!  Nearly :-)

There's still one empty translation:
```sh
#: notmuch/notmuch.c:2300
#, c-format
msgid "Unable to sync %d message due to external mailbox modification"
msgid_plural "Unable to sync %d messages due to external mailbox modification"
msgstr[0] ""
msgstr[1] ""
```

This has two entries.
The first is the singular version, the second is the plural.

Also, I forgot to mention the "fuzzy" entries.
They need translating too.  Sorry :-(

When there are missing translations, sometimes the message compiler will try to be helpful by copying _similar_ messages.
Here's one:

```sh
#: opcodes.h:43
#, fuzzy
msgid "edit the 'Content-ID' of the attachment"
msgstr "Editar el campo 'Content-Language' del adjunto"
```

Some fuzzy entries _might_ save you time.
When you're done, **remove** the 'fuzzy' comment.

When you push to your branch, GitHub will automatically update the PR.
When you're happy, ping me and I'll take another look.

Thanks :heart:

**Comment by Robdres** [comment]
Sure! Sorry about it! Will work on it
Greetings
Roberto

Saludos
Roberto Alvarado

________________________________

**Review by flatcap — APPROVED** [review]
Perfect!  Thank you!

**Comment by flatcap** [comment]
In future, you won't need to create a pull request (unless you have questions).
You can push straight to the `translate` branch and a [GitHub Action](https://github.com/neomutt/neomutt/actions/workflows/translate.yml) will automagically update the [**Leaderboard**](https://neomutt.org/translate).

Thanks!

**Comment by Robdres** [comment]
Perfect! Thank you so much!

________________________________

**Comment by mschilli87** [comment]
¡Muchas gracias! :heart: :tada: :smiley:

**Pull request merged**
