### PR TITLE
test: add compression tests

### PR DESCRIPTION
**Pull request by flatcap**
Add tests for lz4, zlib and zstd compression.

### CODE REVIEW

**Comment by gahr** [comment]
Can't the `test_compress_*` functions be refactored into a common algorithm to test them all?

**Comment by flatcap** [comment]
> Can't the `test_compress_*` functions be refactored into a common algorithm to test them all?

One complication is that they're individually build-conditional.

They _could_ be merged.
But, excluding the compression level limits, the tests aren't _quite_ the same.
They don't _quite_ behave the same way on errors (possibly something that should be fixed).

**Comment by gahr** [comment]
> But, excluding the compression level limits, the tests aren't quite the same.
> They don't quite behave the same way on errors (possibly something that should be fixed).

I think compression levels should be exposed by `ComprOps`, and given `
const struct ComprOps *cops = compress_get_ops("foo");`, you should be able to code the test in exactly the same way no matter the actual value of "foo".

**Comment by flatcap** [comment]
Added:
- min,max compression levels
- validator that uses them

**Pull request merged**
