### PR TITLE
Avoid browsing the remote spoolfile by setting MUTT_SELECT_MULTI attach

### LINKED ISSUE #336: Query: Attach file
This bug was reported by Andrew Duchowski (on the neomutt-users mailing list).

On a Mac, I just changed from mutt to neomutt via
upgrades to macOS Sierra and macports.

In mutt, when I used to 'a'ttach a file and then
press '?' to search the list of folders, two things
happened:

1. I would see my ~/Mail foler
2. mutt would remember which dir I was in if I
   wanted to 'a'ttach again

Now, in neomutt, when I 'a'ttach a file, two
things happen:

1. I see my remote mail spoolfile (e.g., exchange)
   and now I have to press '=' to get to my local
   ~/Mail dir
2. neumutt no longer remembers where I was looking
   at for attachments, consequently I have to press
   '=' again and then descend down a possibly long
   directory branch to get to where I was just a
   second ago.

Is there a .muttrc switch to revert back to the
old functionality?

### PR DESCRIPTION
**Pull request by gahr**
Closes #336 

@neomutt/reviewers Please review. This Works For Me (tm) but I'm not 100% confident that it doesn't fallout in some strange ways.
@P-EB I'd like to have your opinion on this, too.

### CODE REVIEW

**Comment by gahr** [comment]
This is a pseudo-reopen of #365

**Comment by guyzmo** [comment]
browing?

**Comment by flatcap** [comment]
"browsing" but there's no way I'm force-pushing every again :-)

**Comment by guyzmo** [comment]
@gahr please fix the typo ^^

**Pull request merged**
