### PR TITLE
Improve composition of multipart messages

### PR DESCRIPTION
**Pull request by dcpurton**
## Background

The present support for creating multipart emails is basic and suffers from functionality and usability problems. For example,

- Grouped attachments display as a single attachment which cannot be modified or ungrouped.
- Grouped attachments are appended to the list of attachments and can not be made the body of the email if other attachments have been added prior to grouping. See issue #2387.
- Grouping is lost if sending is aborted for any reason (e.g., crypt function fails or failed attachment check) or an email is postponed.

## Goals for this branch

The goal for this branch is to provide better support for both composing multipart/alternative and multipart/multilingual emails.

### Tasks:

- [x] `<group-attachment>` should place multipart/alternative group at position of first tagged attachment rather than end of attachment list.
- [x] Multipart/alternative attachments should display with correct tree structure.
- [x] Attachments (grouped and otherwise) should be able to be moved around in a natural way.
- [x] Support `<edit-message>` when the body of the email is a multipart/alternative attachment.
- [x] Support ungrouping of multipart attachments.
- [ ] Preserve grouping when postponing a message.
- [ ] Provide analogous support for multipart/multilingual attachments.
- [ ] Create tests.
- [ ] Amend documentation.

### Bugs and issues:

- [x] Trying to create a a nested group breaks the email.
- [x] New attachments to an email with a group at the end of the attachment list append to the group, not the top level.
- [x] Detaching parts of a group breaks the email.
- [x] Attachments are being dropped when postponing messages (regression in current code).
- [ ] Segfault when attempting to edit a grouped main body after postponing (regression in current code).

### Future plans:

- Allow attachments to be added to and removed from a group.
- Allow nested groups.
- Provide support for forwarding an email as message/rfc822.

## Questions for discussion

1. Should there be (or is there) a hook to update alternative parts when the first part of a group is edited with `<edit-message>`?
2. When/should a newly added attachment be added to an existing group?

    Current code always adds new attachments at the top level at the bottom of the list of attachments.

3. Should demoting an attachment from a group be allowed if this would result in a group with less than two parts?
4. Although not directly related, should moving the fundamental part be supported? This is somewhat analogous to moving the first part of a grouped attachment.
5. What should happen if you try and delete a multipart/alternative group?
    1. Require ungrouping first? ← Current behaviour of code
    2. Delete group and sub parts?
    3. Delete group and sub parts after asking for confirmation?

### CODE REVIEW

**Comment by flatcap** [comment]
I've created some sample config to help with testing: https://gist.github.com/flatcap/4a5e15f11f76115fb26be963e93ca11f
and a large list of possible tests: https://gist.github.com/flatcap/4db1bf6a1fa8e312af48e8166e732e05
(but it seems like you've already thought of many more cases than I'd considered :-)
I'll have a think through your questions.

**Comment by flatcap** [comment]
The automatic Travis build failed (below).
If you click **details** it'll take you to the build log.

It seems that the build succeeded, but `make test` failed.
You can run `make test` locally, there aren't any extra deps, or you can run individual tests, e.g.
`test/neomutt-test test_mutt_actx_add_attach`

**Comment by dcpurton** [comment]
@flatcap Thanks! I'll look through your test thoughts. But don't get too excited, supporting all this is still going to take me a while :).

> The automatic Travis build failed

So I saw. I was a little over zealous in trimming code.

**Comment by flatcap** [comment]
Wow!  That works well :-)

Would you like to continue adding features?
Or shall we first stabilise at top-level groups and moving?

**Comment by dcpurton** [comment]
> Would you like to continue adding features?
> Or shall we first stabilise at top-level groups and moving?

I think it's probably smart to start with top level grouping.

The problem at the moment is that if you try and group within a group you break the email. I've been looking at making sub groups work, but I think I might move that to the **future plans** section for now. I've never actually seen an email in the wild with nested multipart/alternative attachments. Although I guess I can imagine a use case where you would have multipart/multilingual groups nested in a multipart/alternative group (or vice versa).

I think it's worth doing the things listed in the **tasks** section as a first step (and perhaps the multilingual point as they should probably work the same in a released version), getting that stable and merging if everyone is happy. These seem like a minimum set of features to ensure that things behave in an unsurprising way. Supporting `<edit-message>` to edit the first part of a multipart email body is trivial. But that might not be enough as you likely want to update the alternative parts too. I'm not sure if an existing hook could be used to achieve this or whether a multipart-edited hook would be needed. And I haven't looked at preserving groups when postponing a message yet.

Totally happy to add to or remove from that task list as you see fit though. My own use case is quite simple and is already possible with what I've done so far.

I would like to tidy and optimise my code a bit though. I often don't realise I haven't done something in the best way until I've done it and understood better how things work.

**Comment by flatcap** [comment]
> I think it's probably smart to start with top level grouping.

good

> I think it's worth doing the things listed in the **tasks** section as a first step

great, I'll 

> I would like to tidy and optimise my code a bit though

of course

**Comment by flatcap** [comment]
Rebased over our recent refactoring

**Comment by flatcap** [comment]
Rebased over recent compose changes in master.

**Comment by flatcap** [comment]
Rebased over `master`

**Comment by dcpurton** [comment]
Update: Sorry for the lack of progress on this! Life is in the way, but I still plan to get back to it.

**Comment by flatcap** [comment]
> Sorry for the lack of progress on this!

No worries

> I still plan to get back to it

Great.  I'll keep rebasing it then :-)

**Comment by flatcap** [comment]
Archived to: https://github.com/neomutt/neomutt-old/tree/compose-multipart

**Comment by dcpurton** [comment]
@flatcap , I've finally got time to get back to this and I'm still keen to get this feature merged if there is willingness at your end.

I see why you gave up rebasing with the major refactoring. The code in `compose/functions.c` is definitely much improved.

I've now implemented all the tasks above with the exception of the tests, with which I need some guidance from you.

You can check it out at https://github.com/dcpurton/neomutt/tree/devel/compose-multipart.

The greatest risk for breakage is dealing with postponed messages. I'm confident that it's a lot better than the present implementation. But to be honest the `mutt_send_message` function in `send/send.c` would probably benefit from one of your refactoring efforts … it's a mess. It's difficult to know if I found all the places where modifications are needed.

Oh, and I don't suppose you follow the cricket? :stuck_out_tongue_winking_eye:

**Comment by flatcap** [comment]
> I've finally got time to get back to this

Great!

> I'm still keen to get this feature merged if there is willingness at your end.

Absolutely

> The code in `compose/functions.c` is definitely much improved.

Thanks.  I'm slowly applying that format to all the dialogs.
Independent C functions that work on some shared data.

> I've now implemented all the tasks above with the exception of the tests,
> with which I need some guidance from you.

Great.  I'll try to think of all the ways to test your code.

I'll also have a look at the dependencies of the data and code...
It's a longshot, but it _may_ be possible to create some automated tests.

> You can check it out at `dcpurton/neomutt@devel/compose-multipart`

Got it.
I've pushed it back to the neomutt repo, however GitHub won't let me re-open this PR.

> **The devel/compose-multipart branch was force-pushed or recreated.**

Please can you open a new PR.

> The greatest risk for breakage is dealing with postponed messages.
> I'm confident that it's a lot better than the present implementation.

OK

> But to be honest the `mutt_send_message` function in `send/send.c`
> would probably benefit from one of your refactoring efforts … it's a mess.

Yeah.  That's a terrifying part of the code.
I'll add it to the list.

> It's difficult to know if I found all the places where modifications are needed.

Noted

> Oh, and I don't suppose you follow the cricket?

_sigh_.  What an embarrassment! 🤦🏻

**Comment by flatcap** [comment]
I've pushed a few tidying commits to the branch, and I've discovered a small bug.

Steps:
- Create a small group
- Create a big group below it
- Use `<move-down>` on the small group

When it passes the big group, the selection is in wrong place.

**Comment by dcpurton** [comment]
Looks like there are still some issues there. I just found another one too. I'll fix them.

**Comment by dcpurton** [comment]
@flatcap I fixed the big group bug you found and another bug with reordering attachments in larger groups.

New pull request opened at https://github.com/neomutt/neomutt/pull/3173 so discussion can be continued there.

**Pull request closed without merging**
