### PR TITLE
Don't special-case <stddef.h>

### PR DESCRIPTION
**Pull request by alejandro-colomar**
Fixes: ac6ef83f3229 ("fix: build of imap/auth_sasl.c")
Closes: <https://github.com/neomutt/neomutt/issues/4284>

Builds locally.  Let's see what CI has to say.

---

Revisions:

<details>
<summary>v2</summary>
v2 changes:

-  Workaround macOS violation of POSIX

```
$ git range-diff main neomutt/devel/stddef devel/stddef 
1:  8abe6e5e1 = 1:  8abe6e5e1 .clang-format: Don't special-case <stddef.h>
2:  bf134eaf0 = 2:  bf134eaf0 Sort include <stddef.h>
-:  --------- > 3:  469229425 test/store/common.c: Workaround macOS bug
3:  7066b19ff = 4:  3f3669fd4 .cirrus.yml: DO NOT MERGE: trigger CI on push to test these changes
```
</details>

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
The macOS test fails:

```
test/store/common.c:40:8: error: call to undeclared function 'mkdtemp'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  if (!mkdtemp(path->data))
       ^
1 error generated.
```

That's weird, because that file includes <stdlib.h>, which is what provides mkdtemp(3), according to POSIX.

**Comment by alejandro-colomar** [comment]
Oh well,  these ******** aren't POSIX-compliant, it seems.  The macOS manual page for mkdtemp(3) says they provide it in <unistd.h>.

POSIX:
<https://pubs.opengroup.org/onlinepubs/9699919799/functions/mkdtemp.html>
macOS:
<https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/mkdtemp.3.html>
FreeBSD:
<https://man.freebsd.org/cgi/man.cgi?query=mkdtemp&apropos=0&sektion=0&manpath=FreeBSD+14.0-RELEASE+and+Ports&arch=default&format=html>

It's weird, because FreeBSD provides mkdtemp(3) in the right header.

I'll add a commit adding an include <unistd.h> to that file.

**Comment by alejandro-colomar** [comment]
macOS build passes after including <unistd.h>: <https://github.com/neomutt/neomutt/actions/runs/8970958530>

**Comment by alejandro-colomar** [comment]
@flatcap  If you're happy with it, let me know and I'll drop the last patch (or you can do it; as you prefer).

**Review by flatcap — APPROVED** [review]
Lovely, thanks!

**Pull request merged**
