### PR TITLE
replace qsort() with mutt_qsort_r()

### PR DESCRIPTION
**Pull request by roccoblues**
* replace `qsort()` with `mutt_qsort_r()`, passing an additional data parameter where appropriate
* change `ARRAY_SORT` to accept a data parameter and switch it to `mutt_qsort_r()`
* change `sort_t` to a `qsort_r()` compatible definition
* add `@ingroup sort_api` doxygen label to compatible functions

Also see the discussion in https://github.com/neomutt/neomutt/discussions/3952.

### CODE REVIEW

**Comment by flatcap** [comment]
Where we've lost:
```diff
- * imap_sort_email_uid - Compare two Emails by UID - Implements ::sort_t - @ingroup sort_api
+ * imap_sort_email_uid - Compare two Emails by UID
```

we might want to think about a replacement.
The `sort_t` typedef and the `@ingroup sort_api` Doxygen label give us a [Sort API page](https://neomutt.org/code/group__sort__api.html) in the code docs.

**Review by flatcap — DISMISSED** [review]
The majority of the sort functions only check if `(c_some_var & SORT_REVERSE)`,
so we can probably simplify them all to pass `bool reverse`.

Specifically:

- `alias_sort_address()`
- `alias_sort_name()`
- `alias_sort_unsort()`
- `browser_sort_count()`
- `browser_sort_count_new()`
- `browser_sort_date()`
- `browser_sort_desc()`
- `browser_sort_order()`
- `browser_sort_size()`
- `browser_sort_subject()`
- `crypt_compare_address_qsort()`
- `crypt_compare_date_qsort()`
- `crypt_compare_keyid_qsort()`
- `crypt_compare_trust_qsort()`
- `pgp_compare_address_qsort()`
- `pgp_compare_date_qsort()`
- `pgp_compare_keyid_qsort()`
- `pgp_compare_trust_qsort()`
- `sb_sort_count()`
- `sb_sort_desc()`
- `sb_sort_flagged()`
- `sb_sort_order()`
- `sb_sort_path()`
- `sb_sort_unread()`

In `alias/sort.c` we can eliminate `RSORT()` and `SortAlias`

In `sidebar/sort.c` we can eliminate `SbSortReverse`

In:
- `dlg_select_gpgme_key()`
- `dlg_select_pgp_key()`

Initialise pointer:
- `sort_t f;`

Thanks

**Comment by roccoblues** [comment]
>     * `alias_sort_address()`
>     * `alias_sort_name()`
>     * `alias_sort_unsort()`

done

>     * `browser_sort_count()` 
>     * `browser_sort_count_new()`
>     * `browser_sort_date()`
>     * `browser_sort_desc()`
>     * `browser_sort_order()`
>     * `browser_sort_size()`
>     * `browser_sort_subject()`
>     * `crypt_compare_address_qsort()`
>     * `crypt_compare_date_qsort()`
>     * `crypt_compare_keyid_qsort()`
>     * `crypt_compare_trust_qsort()`
>     * `pgp_compare_address_qsort()`
>     * `pgp_compare_date_qsort()`
>     * `pgp_compare_keyid_qsort()`
>     * `pgp_compare_trust_qsort()`

^^ all those I already did. Or did I miss something?

>     * `sb_sort_count()`
>     * `sb_sort_desc()`
>     * `sb_sort_flagged()`
>     * `sb_sort_order()`
>     * `sb_sort_path()`
>     * `sb_sort_unread()`

done
 
> In `alias/sort.c` we can eliminate `RSORT()` and `SortAlias`

done

> In `sidebar/sort.c` we can eliminate `SbSortReverse`

done
 
> Initialise pointer:
> 
>     * `sort_t f;`

Initialized with `NULL` now. Or should we set it to the default sort function?

**Comment by flatcap** [comment]
Looking good (and efficient) now!

There are a few small tasks left, if you're not yet tired of sorting...
Thanks!

### Browser: Remove `sort_reverse` from the compare functions

The browser sort uses a wrapper, `browser_compare()`.
We can do the `sort_reverse` handling, there instead of in:

- `browser_sort_count()` 
- `browser_sort_count_new()` 
- `browser_sort_date()` 
- `browser_sort_desc()` 
- `browser_sort_order()` 
- `browser_sort_size()` 
- `browser_sort_subject()` 

### Browser: Eliminate `$browser_sort_dirs_first` and `switch`

To sort the browser, we need three things:
- Value of `$browser_sort_dirs_first`
- Sort type: `c_sort_browser & SORT_MASK`
- Sort direction: `c_sort_browser & SORT_REVERSE`

We can pass these to `browser_compare` in a new `struct`.
For efficiency, we can pass two bools and a sort **function**.

### Tag a couple of function comments

Add ` - @ingroup sort_api` so that they're listed on the sort api page:

- `mutt_compare_emails()`
- `mutt_inbox_cmp()`

### Use `mutt_numeric_cmp()` for comparing numbers

This is useful for large numbers like dates to prevent under/overflow and other numbers for consistency.

- `alias_sort_unsort()` 
- `browser_sort_count()` 
- `browser_sort_count_new()` 
- `browser_sort_date()` 
- `browser_sort_order()` 
- `browser_sort_size()` 
- `sb_sort_count()` 
- `sb_sort_flagged()` 
- `sb_sort_order()` 
- `sb_sort_unread()`

**Comment by roccoblues** [comment]
> There are a few small tasks left, if you're not yet tired of sorting...

don't worry, sometimes it takes a couple of iterations.

I've done the requested changes. Please have another look. I really like how simple the browser sort functions have become now.

**Review by flatcap — APPROVED** [review]
Fantastic job.
Thanks!

**Pull request merged**
