### PR TITLE
Functional and unit testing framework

### PR DESCRIPTION
**Pull request by guyzmo**
Adds the necessary for both unit testing and functional testing.
Unit testing will require building the code towards a shared library
Functional testing works using the Lua feature cf #298

For the CI script to work, you need to give:

* `${SOURCES}` the path to the checked out sources
* `${BUILD}` the path to the build directory

`build.sh` will build, and patch the makefiles at the `${BUILD}` target directory.
And `run_tests.sh` will run both tests.

cf #414

### CODE REVIEW

**Comment by guyzmo** [comment]
so, the next step will be to work out automatic installation of the dependencies:

* LuaJit 2.0 for the unit tests, and the busted framework for LuaJit (or Lua 5.1)
* Lua ≥5.2 for the functional tests and compilation of mutt (should be there), and the busted framework for Lua ≥5.2.

**Comment by toogley** [comment]
As far as i understand, unit tests should not rely on dependencies (by that i mean typical things like databases, external servers, internet connection, filesystem, etc. pp.) (I have read this in a book called ["The art of unit testing"](https://www.manning.com/books/the-art-of-unit-testing-second-edition?a_bid=f6ea80f5&a_aid=iserializable)). 

How would you solve this issue with your minimal unit testing framework? That means, how would you mock external dependencies, such as imap server, notmuch database, maildir, etc. ?

(I'm not sure if the answer to this question is different to @gahr 's [approach](https://github.com/neomutt/neomutt/issues/428), therefore i ask, just to be sure.)

**Comment by guyzmo** [comment]
> As far as i understand, unit tests should not rely on dependencies (by that i mean typical things like databases, external servers, internet connection, filesystem, etc. pp.) (I have read this in a book called "The art of unit testing").
> How would you solve this issue with your minimal unit testing framework? That means, how would you mock external dependencies, such as imap server, notmuch database, maildir, etc. ?

cf my other post: the whole point of using a dynamic language is to make it easier to write mockups for all the dependency. What's important with unit testing is not to rely on no dependencies, but not use the dependencies and the runtime environment the program runs in. You should consider that like petridish experiments, where you use tooling that's specially crafted for the task of testing.

**Comment by flatcap** [comment]
This branch has been archived to: https://github.com/neomutt/neomutt-old/tree/testing/testing

**Pull request closed without merging**
