### PR TITLE
Support of relative paths sourcing and cyclic source detection

### LINKED ISSUE #282: Allow the 'source' command to use relative paths
Add the source command that will source external configuration files.

## Syntax

* to source a file located **relatively** to current configuration file:

```
source path/to/file
```

* to source a file in an **absolute** location:

```
source /path/to/file
```

as referenced by issues #281, #234 and #76.

### PR DESCRIPTION
**Pull request by guyzmo**
Added HEAP/FILO structure and global singleton to contain the the list
of config files that have been sourced, and detect cyclic sourcing.
Implemented with a simple heap API:

- `path_heap_push()`
- `path_heap_pop()`
- `path_heap_front()`
- `path_heap_find()`

Added a new method `to_absolute_path()` to convert a path into an absolute
path, relatively to another config file's path. Using POSIX methods to
do so, adding libgen's header in `mutt.h`.

fixes #282

### CODE REVIEW

**Comment by guyzmo** [comment]
Currently the whole heap code is in `init.c` just next to the place of use. 
Either put the whole heap stuff inside its own compilation unit and/or plan the path to #162.
The good side of the heap abstraction I'm suggesting is that it can easily be switched.

**Comment by guyzmo** [comment]
if you're ok with my changes, I'll move the heap stuff in `muttlib.c` along with `mutt_*_list`. ☺

**Comment by guyzmo** [comment]
suggestion for changes:

- replace the `struct config_path_heap` with `LIST*`,
- keep a list of loaded script files in a global context,
- keep the heap static to the compilation unit,
- move all the data structure stuff in muttlib compilation unit

**Comment by flatcap** [comment]
I can't get this to work at all.

Wherever I run mutt from, I get:
- Error: Cyclic sourcing of configuration file '/home/mutt/.muttrc'.

Adding `-F` doesn't help either.

**Comment by guyzmo** [comment]
yup, my last commit did not help, a few preconditions that were designed in my heap algorithms went missing when I merged with muttlib's LIST implementation.

**Comment by guyzmo** [comment]
@flatcap should be fixed, sorry for the issue!

**Comment by flatcap** [comment]
I've just given it a good thrashing and everything works beautifully.

I tried config:
- relative to the current directory
- relative to other files
- mix and matching absolute and relative dirs
- a cycle of length 3
- a cycle of length 100
- an insane 4 dir deep, 775 config file loop of random sources

I just need to look at, and understand, the source.

**Comment by guyzmo** [comment]
the implementation is rather straightforward:

* in `muttlib.c`
 * I've added a heap interface to the LIST structure (to keep DRY).
 * that interface adds a push front method (`mutt_push_heap()`) and a pop front method (`mutt_pop_heap()`)
* in `init.c`
 * I've added `to_absolute_path` that converts a given path string to absolute, relatively to a reference path string. That reference path shall always be a filename (the last part is of that path is removed).
 * the `source_rc()` function is taking a file path:
   * converts it to absolute relative to the file on the top of the heap, 
   * looks up if that file is already in the heap
   * if not, sources it.

So at the end of the execution, the Heap should be an empty pointer. TBH, the *one improvement* would be to make the pointer `MuttrcHeap` a static variable local to `source_rc()`.

**Comment by flatcap** [comment]
@gahr found a problem when using pipes in a config file, e.g.
```
source "gpg -q -d ~/.mutt/password.gpg |"
```
gives the error: "Error in muttrc, line 6"

**Comment by gahr** [comment]
The error is
`Error: issue converting path to absolute (No such file or directory)`

**Pull request closed without merging**
