### PR TITLE
Fix up slashes in imap_fix_path

### LINKED ISSUE #2422: imap folder completion doesn't use server delimiter
As discussed on IRC, here is my bug report:

Configuration variable:
```
set folder="imaps://user@server.de/INBOX"
```

(Sidenote: Same results for `set folder="imaps://user@server.de/INBOX."`  (with trailing dot)

## Expected Behaviour
TAB folder completion should use defined imap_delim_char

## Actual Behaviour

1) I type "c" to change folders:
 -> Open mailbox: =Archiv\<TAB\>
Result: BEEP

LOG:
```
[2020-07-10 17:50:44]<2> mutt_complete() completing =Archiv
[2020-07-10 17:50:44]<2> mutt_socket_write_d() 4> c0011 LIST "" "INBOX/Archiv%"
[2020-07-10 17:50:44]<5> mutt_socket_readln_d() 4< c0011 OK List completed (0.001 + 0.000 secs).
[2020-07-10 17:50:44]<3> imap_cmd_step() IMAP queue drained
```

2) I type "c" to change folders:
 -> Open mailbox: imaps://user@server.de/INBOX.Archiv\<TAB\>

Result: Line switches to:
 -> Open mailbox: +Archive

```
[2020-07-10 17:49:53]<2> mutt_complete() completing imaps://user@server.de/INBOX.Archiv
[2020-07-10 17:49:53]<2> mutt_socket_write_d() 4> c0007 LIST "" "INBOX.Archiv%"
[2020-07-10 17:49:53]<5> mutt_socket_readln_d() 4< * LIST (\HasNoChildren) "." INBOX.Archive
[2020-07-10 17:49:53]<5> mutt_socket_readln_d() 4< c0007 OK List completed (0.001 + 0.000 secs).
[2020-07-10 17:49:53]<3> imap_cmd_step() IMAP queue drained
```

I hit \<ENTER\> which leads to ERROR message:
 Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).

LOG:
[2020-07-10 17:52:24]<1> mx_path_probe() unable to stat +Archive: No such file or directory (errno 2)

So, to be exact this might be two separate issues.

Thanks!
 Andy

## NeoMutt Version
```
NeoMutt 20200626
Copyright (C) 1996-2016 Michael R. Elkins und andere.
NeoMutt übernimmt KEINERLEI GEWÄHRLEISTUNG. Starten Sie 'neomutt -vv', um
weitere Details darüber zu erfahren. NeoMutt ist freie Software.
Sie können es unter bestimmten Bedingungen weitergeben; starten Sie
'neomutt -vv' für weitere Details.

System: Linux 5.3.0-51-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
GnuTLS: 3.6.14
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --sqlite --autocrypt

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-Ngf0Dg/neomutt-20200626+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Standard Einstellungen:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Einstellungen bei der Kompilierung:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

### PR DESCRIPTION
**Pull request by gahr**
Fixes #2422

This is an alternative approach to #4358, with the goal of making this comment true: https://github.com/neomutt/neomutt/blob/1c5c53079df4b52458de6a1c19bb9dbe08d0abb3/complete/complete.c#L80

The idea is that if we have a delim other than a slash, e.g., `.`, we can change slashes into the delim, so expansions such as `+Foo`, when `folder=imaps://..../INBOX` end up correctly being `imaps://.../INBOX.Foo`.

### CODE REVIEW

**Review by roccoblues — APPROVED** [review]
This looks ok for me. However I'd feel more confident with the change if we'd have some tests for `imap_path_canon`. How hard would they be to add?

**Comment by gahr** [comment]
> This looks ok for me. However I'd feel more confident with the change if we'd have some tests for `imap_path_canon`. How hard would they be to add?

Probably not terribly hard. Let me take a look.

**Comment by gahr** [comment]
> > This looks ok for me. However I'd feel more confident with the change if we'd have some tests for `imap_path_canon`. How hard would they be to add?
> 
> Probably not terribly hard. Let me take a look.

Alright, so, `imap_path_canon` only does interesting things when we have `NeoMutt->accounts`.. other than that, it just calls `imap_fix_path` (and now `imap_fix_path_with_delim`). I suggest I add tests to those instead.

**Comment by gahr** [comment]
```
ld: error: duplicate symbol: imap_exec
>>> defined at msg_set.c:49 (test/imap/msg_set.c:49)
>>>            test/imap/msg_set.o:(imap_exec)
>>> defined at command.c:1305 (imap/command.c:1305)
>>>            command.o:(.text+0x45C8) in archive libimap.a
```

alright I'm not going to take care of [redefined](https://github.com/neomutt/neomutt/blob/990b3d644e12b14af6ce77d0462f3517887b7e0b/test/imap/msg_set.c#L48-L55) [functions](https://github.com/neomutt/neomutt/blob/990b3d644e12b14af6ce77d0462f3517887b7e0b/imap/command.c#L1304) in this PR :/

**Pull request merged**
