### PR TITLE
Allow index-style searching in postpone menu

### PR DESCRIPTION
**Pull request by nabijaczleweli**
* **What does this PR do?**
Implements index-style searching in postpone menu

* **What are the relevant issue numbers?**
#2428

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Done

**Comment by flatcap** [comment]
It works :-)

I'm wondering if we can do this without having to alter `Menu`, though.

I hoped we could add a line to `functions.c`
https://github.com/neomutt/neomutt/blob/60831ec79e281913fbe1663ba3b441aee5507792/functions.c#L526-L530

Nope!

It might still be possible by setting `Menu->search`.
(it's used in [`alias/dlgquery.c`](https://github.com/neomutt/neomutt/blob/master/alias/dlgquery.c#L348) and [`browser.c`](https://github.com/neomutt/neomutt/blob/master/browser.c#L1405))
The Menu calls that for each row, looking for a match.

I _think_ we might have enough info for it to work.
Please could you have a look.

**Comment by nabijaczleweli** [comment]
I had that thought too, but AIUI the `Menu->search` framework (https://github.com/neomutt/neomutt/blob/60831ec79e281913fbe1663ba3b441aee5507792/menu.c#L1151-L1158 and https://github.com/neomutt/neomutt/blob/60831ec79e281913fbe1663ba3b441aee5507792/mutt_menu.h#L119-L127) don't give us enough freedom to implement this search, since they limit us to a regex with stiff pre/post processing

**Comment by flatcap** [comment]
> don't give us enough freedom to implement this search

Fair enough.

**Comment by nabijaczleweli** [comment]
Rebased

**Pull request merged**
