### PR TITLE
* lib.c (safe_strdup): Don't return a NULL pointer when trying to cop…

### PR DESCRIPTION
**Pull request by darnir**
Potential fix for #567

### CODE REVIEW

**Comment by gahr** [comment]
Please don't do this - it will likely break a zillion of other things. Mutt runs under the assumption that `safe_strdup` doesn't allocate a one-byte `"\0"` string but return NULL instead. Client code is supposed to use `NONULL` with the return value.

**Comment by darnir** [comment]
I agree. I mentioned it in my original issue that this will likely break things. I quickly cooked this up and it seemed to work (didn't crash my mutt while I viewed and handled my mail)

**Comment by gahr** [comment]
Of course it won't crash your mutt. You're killing an optimization and changing an assumption, though. What about you use `NONULL` like it's done all over the place instead?

**Comment by guyzmo** [comment]
I agree with @gahr. This is a false good idea. Whether returning a NULL pointer for empty strings being a good idea is debatable, that choice has been made 19 years ago. So I'm closing that issue, and fix my own mistake!

**Pull request closed without merging**
