### PR TITLE
New configure option --enable-everything

### PR DESCRIPTION
**Pull request by darnir**
Currently this configure option will enable:
* GPGME
* PGP
* SMIME
* Sidebar
* Compressed Folder Support
* Notmuch

In the future, this option will also enable:
* Header Cache (tokyocabinet)
* POP3
* SMTP
* IMAP
* GnuTLS
* NNTP

### CODE REVIEW

**Comment by darnir** [comment]
P.S.: This is broken since it does not allow overriding the value set by --enable-everything

**Comment by flatcap** [comment]
hi @darnir.
That's starting to look good.

On IRC you asked:
> --enable_everything will require a significant change to configure.ac.
> Are we okay with that?

Yes, I'm happy with that.
Your work means that our `configure` is already superior to Mutt's.
If Mutt makes any changes, it's more likely to be a new feature than major restructuring.

**Comment by darnir** [comment]
Turns out the restructuring wasn't really required. I could have managed without. But it's done now and I like how it looks. So it stays. 

Also, I've fixed the issue with overriding. Small subtlety that was missed. I'll send an updated patch soon

**Comment by darnir** [comment]
Closed in favour of #264

**Pull request closed without merging**
