### PR TITLE
pager: monumental refactoring part 1.

### PR DESCRIPTION
**Pull request by ngortheone**
* **What does this PR do?**

Begins monumental pager refactoring:
- introduces `PagerMode` enum
- removes `IsEmail`, `IsAttach` and `IsMsgAttach` macros
- splits `struct Pager` into `struct PagerData` and `struct PagerView`
- does some code readability improvements that help @ngortheone to stay a bit more sane
- adds tons of comments

### CODE REVIEW

**Comment by flatcap** [comment]
I've rebased [[devel/refactor]](https://github.com/neomutt/neomutt/tree/devel/refactor) over `master`.
I've also rebased [[devel/pager-break-1]](https://github.com/neomutt/neomutt/tree/devel/pager-break-1) over `[devel/refactor]` and put it in [[devel/pager-break-2]](https://github.com/neomutt/neomutt/tree/devel/pager-break-2).

**Comment by ngortheone** [comment]
@flatcap this part is done. It compiles and works.
I will start working diving into input hacks in the next PR

**Comment by ngortheone** [comment]
@flatcap 
the easiest way to read this PR is:
- `lib.h` first
- then everything else
- and `pager.c` last

**Comment by ngortheone** [comment]
@flatcap 

I have removed the rant in the comments.
I also decided to continue and removed TopLine check out of the main event loop (see commit message)


P.S. this PR grows, we should merge it soon.

**Comment by ngortheone** [comment]
Squashed some commits together, to make each commit build-able (removed WIP intermediate commits)

**Review by flatcap — APPROVED** [review]
I've moved your original branch to [[devel/pager-break-orig]](https://github.com/neomutt/neomutt/tree/devel/pager-break-orig).

I've done a bunch of tidying-up:
- Killed all the trailing whitespace
- Clang-formatted (removed your clang comments)
- Introduced some `{}`s for `if`s, etc, that now use more than one line
- Introduced some `()`s for complex logic
- Renamed `PagerView` variables to `pview`
- Renamed `PagerData` variables to `pdata`
- Reorganised a few commits to reduce churn
- Factored out all the TODO comments into [[devel/pager-todo]](https://github.com/neomutt/neomutt/tree/devel/pager-todo)
  I've left the majority of your comments, which are informative,
  but moved the TODOs to a separate branch as they're more for your benefit.

**Pull request merged**
