### PR TITLE
Rename $attribution and $post_indent_string

### LINKED ISSUE #3715: Rename `$post_indent_string` to `$attribution_trailer`?
Not so much a feature request as more inspirational suggestion:

Maybe rename `$post_indent_string` to `$attribution_trailer` (and also `$attribution` to `$attribution_intro`).
This would make it consistent with `$forward_attribution_intro`/`$forward_attribution_trailer`.

### PR DESCRIPTION
**Pull request by whitney-cumber**
* **What does this PR do?**

Rename $attribution to $attribution_intro and $post_indent_string to $attribution_trailer.
Some minor rewording in the documentation.

* **What are the relevant issue numbers?**

Fixes #3715

### CODE REVIEW

**Comment by gahr** [comment]
Nice job - I see potential for refactoring around the `mutt_make_attribution_(intro|trailer)` functions to reduce duplication. Can you make a static `make_attribution` function that takes the configured string and implements the common logic?

**Comment by whitney-cumber** [comment]
> Nice job - I see potential for refactoring around the mutt_make_attribution_(intro|trailer) functions to reduce duplication. Can you make a static make_attribution function that takes the configured string and implements the common logic?

Sorry to disappoint but I cannot program C, renaming stuff yes but beyond that I have to pass.

**Comment by gahr** [comment]
> > Nice job - I see potential for refactoring around the mutt_make_attribution_(intro|trailer) functions to reduce duplication. Can you make a static make_attribution function that takes the configured string and implements the common logic?
> 
> Sorry to disappoint but I cannot program C, renaming stuff yes but beyond that I have to pass.

No worries, do you mind if I push what I had in mind to this branch?

**Comment by whitney-cumber** [comment]
Not at all, feel free to do whatever you want.

**Pull request merged**
