### PR TITLE
Accept abbreviated commands

### LINKED ISSUE #701: Please accept :se as a synonym for :set
This is a minor item, but a very regularly encountered pain point for me.

Vim accepts commands starting with a colon, just like mutt does. However, vim allows abbreviating commands using any unambiguous prefix. In particular, you can write `:se` instead of `:set`. I regularly find myself typing this in mutt and expecting it to work (e.g. `:se mime_forward=yes`), only to get an error, and have to go back and change it to `:set`.

I don't know if mutt should *in general* move to accepting unambiguous prefixes, but please consider accepting `:se` in particular as a synonym for `:set`.

### PR DESCRIPTION
**Pull request by flatcap**
Many commands could be abbreviated and still be unique, e.g.
- `:co` instead of `:color`
- `:so` instead of `:source`

This PR allows all the shortest abbreviations for commands, with one exception: `:se` is allowed for `:set`

Closes #701

### CODE REVIEW

**Comment by gahr** [comment]
A slightly dangerous thing is that the addition of any command must now trigger a review of unrelated lines in init.h to catch potential clashes of minimum prefix. Is that an issue? Just a thought..

**Comment by flatcap** [comment]
That's a good point.
A simple solution would be to add comments to that effect.
Alternatively, we could generate the lengths at startup.
(the command list is now sorted, so it would be fairly simple to do)

**Comment by gahr** [comment]
+1 for the runtime generation of prefixes. However, I'm not fond of exceptions (for set).
How about we just alias se to set? Is the whole set (no pun intended) really needed?

**Comment by flatcap** [comment]
I've looked through my logs and I only tend to `:set` and `:source`.  I'd benefit from `:so`.

Do we need the others?
Not really, but I don't see any harm in having them.

As for the runtime generation, I'll have a think how to do it.
(I used vim and awk for the initial list)

**Comment by gahr** [comment]
I really don't know, I feel a bit uncomfortable with this one. I think what's worrying me is that prefixes can change between compilations - addition / removal of commands or potentially even different configure options - which will make them useless or even incorrect at muttrc level.
Having slept on it some more, I think I'd prefer to hardcode just the set of prefixes people require as aliases.
Just my .2CHF ;)

**Comment by flatcap** [comment]
This PR works, but it's been decided to solve the problem in another way.
See the comments for #701

**Comment by toogley** [comment]
@flatcap when it has been decided to solve it differently, is there a reason why this PR is still open then?

**Comment by flatcap** [comment]
> is there a reason why this PR is still open

It contains a _little_ useful info and the PR's a good template of where the code needs changing.
You can kill it next week.

**Comment by gahr** [comment]
An alternative approach was preferred.

**Pull request closed without merging**
