### PR TITLE
Translate

### PR DESCRIPTION
**Pull request by yuzibo**
* **What does this PR do?**
update zh_CN
* **Screenshots (if relevant)**
No

* **What are the relevant issue numbers?**
No

### CODE REVIEW

**Comment by yuzibo** [comment]
I just want to push the update to the translate branch. Sorry.

**Comment by flatcap** [comment]
I see that you've just merged this into translate.  Thanks.
There's not much I can do to review the translations since my Mandarin is limited to 你好 and 谢谢 :-)

**Comment by yuzibo** [comment]
Haha, I think @l2dy will do review for that.
Welcome to learn more Chinese :)

**Comment by l2dy** [comment]
FYI, you should remove the `fuzzy` attribute when you finish a translation.

**Pull request closed without merging**
