### PR TITLE
notmuch: clean-up

### PR DESCRIPTION
**Pull request by Austin-Ray**
**What does this PR do?**

This is a long-lived branch with the goal of cleaning up the notmuch subsystem. It's goals are to address code rot, improve code documentation, and remove special cases for notmuch. This PR is meant for garnering feedback and will be merged into master on frequently.

This is not intended to introduce new features, but to improve the robustness of existing ones.

### CODE REVIEW

**Comment by flatcap** [comment]
> https://github.com/neomutt/neomutt/pull/1387/commits/c9cc8c377ff798ecbadcca1a5412f753701ba2d7 Removed all instances of `notmuch://` with a constant, NmUriProtocol.

This sounds good in principle; it's a shame about the five `strlen()`s it introduces.

If the constant had been `#define`d, you could use `sizeof(NmUriProtocol) - 1`.
The compiler would only create **one** string and evalutate the length to a constant.

The alternative would be a `NmUriProtocolLen`.  Hmm...

I've had a quick skim through the other commits.
They look good.  I'll have a closer look tomorrow.

**Comment by Austin-Ray** [comment]
>  This sounds good in principle; it's a shame about the five strlen()s it introduces.

Would the compiler optimize the calls?

If not, I would prefer the variable approach of `NmProtocolLen = mutt_str_strlen(...)`. It results in less duplication and is easier to grok than `sizeof(NmUriProtocol) - 1` (I did not know about that.)

**Comment by Austin-Ray** [comment]
Rebased previous changes onto master and added commit 58b2b15.

**Comment by Austin-Ray** [comment]
I have incorporated your change and rebased onto master.

Unfortunately, `NmUriProtocolLen` is included in `notmuch/notmuch_private.h` since `notmuch/nm_db.c` utilises it in `nm_db_get_filename(...)`, but we're not exposing the URI protocol outside of `notmuch/mutt_notmuch.c`.

If you have an idea for removing `NmUriProtocolLen` from `notmuch/nm_db.c`, I will be happy to incorporate it.

**Comment by flatcap** [comment]
That'll do for now.
Merged as 8d4abed69, branch reset.

**Comment by Austin-Ray** [comment]
My most recent commit might be a bit "controversial" depending on your coding preference. 

It moves `nm_db_is_longrun(...)` checks into `nm_db_release(...)` to reduce programmer error, but at reading a `nm_db_release(...)` call may be misleading since it won't do anything for long-run databases.

**Comment by Austin-Ray** [comment]
Rebased onto master

**Comment by Austin-Ray** [comment]
@flatcap I haven't made much progress on this recently. If you want to merge these commits into master, feel free to.

**Comment by Austin-Ray** [comment]
This subsystem is now `Context`-free!

**Pull request closed without merging**
