### PR TITLE
Rework the "inbox-first" implementation to make code self-explanatory

### PR DESCRIPTION
**Pull request by gahr**

### CODE REVIEW

**Comment by gahr** [comment]
@neomutt/reviewers Please review. I think I got it right this time, but some testing with different setups might be neat. Thanks!

**Comment by gahr** [comment]
This is a regression, I'd like to have it in the next release.

**Comment by gahr** [comment]
I'm not fond of that name either, but couldn't come up with anything better yet. I'm open to suggestions.

Regarding your test, that is exactly what is mentioned in the commit message of c2de191.

**Comment by guyzmo** [comment]
it could be `mutt_find_inbox()` or mutt_resolve_inbox()`

**Comment by gahr** [comment]
or inbox_first_sort

**Comment by gahr** [comment]
.. or better still mutt_inbox_cmp

**Comment by flatcap** [comment]
> or inbox_first_sort

Hmm, Yoda-like that is.

> .. or better still mutt_inbox_cmp

OK, that's a bit clearer.

**Comment by gahr** [comment]
Feel free to modify and merge if you feel like it. Otherwise I'll commit the name change tomorrow.

**Pull request merged**
