### PR TITLE
Norwegian Bokmål translation

### PR DESCRIPTION
**Pull request by comradekingu**
Don't know if this passes the build. (Probably not)
It is quite grim trying to deal with just the one file, so I propose setting up shop on Hosted Weblate (or a self-hosted instance) for translations.

Didn't translate the actual license.
Started with the da.po file, but removed authors from it to not send unwanted e-mails there.

I have a big list of source string errors and improvements.

### CODE REVIEW

**Comment by flatcap** [comment]
Welcome to NeoMutt, @comradekingu!

Getting a translation started is a Herculen task.
Thans you :heart:

> Don't know if this passes the build. (Probably not)

Yep, it doesn't.
I've pushed your work, and some fixes, to the [[translate]](https://github.com/neomutt/neomutt/tree/translate) branch

The fixes (5710939ce2f61e7f487d79814f80c3b9c199ad12) were trivial:
- Missing/extra `"`
- Mismatch of `\n`
- Mismatch of `%d`

Before you push, you can check your work locally:

```sh
msgfmt --statistics -c -o /dev/null po/nb_NO.po
```

https://neomutt.org/translate

> It is quite grim trying to deal with just the one file, so I propose setting up shop on Hosted Weblate (or a self-hosted instance) for translations.
> 
> Didn't translate the actual license.
> Started with the da.po file, but removed authors from it to not send unwanted e-mails there.
> 
> I have a big list of source string errors and improvements.

**Comment by flatcap** [comment]
The changes have been pushed into the [[translate]](https://github.com/neomutt/neomutt/tree/translate) branch.

**Comment by comradekingu** [comment]
@flatcap 
I think some stuff isn't wrapping at 80 lines too.
nb_NO is actually all done, with liberal fuzzifying also covering the greater goal of getting the English into shape.

**Comment by flatcap** [comment]
>  I think some stuff isn't wrapping at 80 lines too.

Most of the strings in the **code** are wrapped at 80 chars,
so it makes sense (to me) to **not** wrap the lines in the `.po` file (they just 80 chars + `msgstr`).

This means that the strings closely match the code and are easily `grep`-able.
All the gettext CLI tools have a `--no-wrap` option.

> nb_NO is actually all done

Ah!  I wondered if it was

> with liberal fuzzifying

Note: "fuzzy" translations don't get used by NeoMutt (that's how gettext works).
"fuzzy" implies that the translation was a machine's guess.
You'll need to remove them to get full coverage.

However, you're welcome to add any other comments to the header or strings.
The gettext tools are pretty clever at keeping your comments, whilst syncing to the source.

> Didn't translate the actual license.

OK, fair enough.  Some translators have, some haven't

The "This program is free software..." is standard text,
so there are probably standard translations out there too.

> ... greater goal of getting the English into shape

Hmm... interesting :-)

Over the years, some of the other translators and I have tried to tidy the translations,
e.g. reusing phrases to reduce the number of strings.

NeoMutt's a complex app and 80 chars is a tight window to work to.

I welcome any suggestions for improvements.

**Comment by flatcap** [comment]
I've spotted a missing translation:

https://github.com/neomutt/neomutt/blob/5710939ce2f61e7f487d79814f80c3b9c199ad12/po/nb_NO.po#L4519-L4522

**Comment by comradekingu** [comment]
@flatcap 
Don't know why I was assigned this, or what to do about it.
I was removed from the translator team, and stopped using the software after I found out it has a CoC.
Thanks for all the good years.

**Comment by flatcap** [comment]
Don't worry, I was just doing a little housekeeping of old pull requests -- adding labels and setting owners

**Pull request closed without merging**
