### PR TITLE
Fix sidebar on new/removed mailboxes

### PR DESCRIPTION
**Pull request by flatcap**
After the refactor 093f19824, the Sidebar was ignoring notifications about new or removed mailboxes.

- Handle new Mailboxes
- Handle removed Mailboxes
- Ensure painting is done when there are only hidden Mailboxes
- Refactor for clarity

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
c157ef279ec8d4d90a2adb88df14e62d9b30da61 fixes #2620 and #2623 for me

**Comment by flatcap** [comment]
> c157ef279ec8d4d90a2adb88df14e62d9b30da61 fixes #2620 and #2623 for me

Brilliant!
I'm still testing this, but I'm nearly done.

**Comment by flatcap** [comment]
@nabijaczleweli @gahr 
I'm done.
- sidebar is more robust
- `mailboxes` and `unmailboxes` should work correctly
- (un)subscribe from/to Imap mailboxes should adjust the sidebar correctly
- refactored `parse_unmailboxes` to make it easier to follow

Please can you give this one last test.
Thanks.

**Comment by nabijaczleweli** [comment]
Works for me

**Comment by gahr** [comment]
Works nicely so far, thanks!

**Pull request merged**
