### PR TITLE
upgrade `assert()`

### PR DESCRIPTION
**Pull request by flatcap**
Replace system `assert()` macro with a custom `ASSERT()` macro.

There are three distinct advantages to the new macro.

1. We can call `endwin()` to reset the screen mode.
2. A debugger will stop **ON** the macro, rather than about 6 levels beneath it.
3. You can continue running NeoMutt by stepping over the `ASSERT()`

---

Inspiration from Chris Wellons' https://nullprogram.com/blog/2022/06/26/

---

This PR upgrades `assert()` to reset the screen and optionally print a backtrace.
It works, if you enable `--debug-backtrace` and outputs:

```
NeoMutt 20240425-37-55fed8
Backtrace
    assertion_dump() ip = 21, sp = 7ffd651127a0
    op_print() ip = 4c, sp = 7ffd651127d0
    index_function_dispatcher() ip = 14e, sp = 7ffd65112820
    dlg_index() ip = b70, sp = 7ffd65112890
    main() ip = 2a41, sp = 7ffd65112950

index/functions.c:2080:op_print() -- assertion failed ((priv->menu->current % 2) == 1)
Illegal instruction (core dumped)
```

---

In the debugger, if you `j 2081` (jump to line 2081), NeoMutt will resume running.

```c
2075│ /**
2076│  * op_print - Print the current entry - Implements ::index_function_t - @ingroup index_function_api
2077│  */
2078│ static int op_print(struct IndexSharedData *shared, struct IndexPrivateData *priv, int op)
2079│ {
2080├─> ASSERT((priv->menu->current % 2) == 1);
2081│   struct EmailArray ea = ARRAY_HEAD_INITIALIZER;
2082│   ea_add_tagged(&ea, shared->mailbox_view, shared->email, priv->tag_prefix);
2083│   mutt_print_message(shared->mailbox, &ea);
2084│   ARRAY_FREE(&ea);
2085│
2086│   /* in an IMAP folder index with imap_peek=no, printing could change
2087│    * new or old messages status to read. Redraw what's needed.  */
2088│   const bool c_imap_peek = cs_subset_bool(shared->sub, "imap_peek");
2089│   if ((shared->mailbox->type == MUTT_IMAP) && !c_imap_peek)
2090│   {
2091│     menu_queue_redraw(priv->menu, (priv->tag_prefix ? MENU_REDRAW_INDEX : MENU_REDRAW_CURRENT));
2092│   }
2093│
2094│   return FR_SUCCESS;
2095│ }
```

### CODE REVIEW

**Comment by roccoblues** [comment]
```
pager/dlg_pager.c:161:10: error: variable 'result' is used uninitialized whenever switch case is taken [-Werror,-Wsometimes-uninitialized]
  161 |     case PAGER_MODE_UNKNOWN:
      |          ^~~~~~~~~~~~~~~~~~
pager/dlg_pager.c:167:10: note: uninitialized use occurs here
  167 |   return result;
      |          ^~~~~~
pager/dlg_pager.c:162:10: error: variable 'result' is used uninitialized whenever switch case is taken [-Werror,-Wsometimes-uninitialized]
  162 |     case PAGER_MODE_MAX:
      |          ^~~~~~~~~~~~~~
pager/dlg_pager.c:167:10: note: uninitialized use occurs here
  167 |   return result;
      |          ^~~~~~
pager/dlg_pager.c:141:31: note: initialize the variable 'result' to silence this warning
  141 |   const struct Mapping *result;
      |                               ^
      |                                = NULL
2 errors generated.
make: *** [pager/dlg_pager.o] Error 1
```

**Comment by roccoblues** [comment]
successful assert:

```
❯ lldb ./neomutt
(lldb) target create "./neomutt"
Current executable set to '/Users/dennis/projects/neomutt/neomutt' (arm64).
(lldb) run
Process 36208 launched: '/Users/dennis/projects/neomutt/neomutt' (arm64)
main.c:598:main() -- assertion failed (1==0)
Process 36208 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1000201f0)
    frame #0: 0x00000001000201f0 neomutt`main(argc=1, argv=0x000000016fdfd730, envp=0x000000016fdfd740) at main.c:598:3
   595
   596    init_locale();
   597
-> 598    assert(1==0);
   599
   600    EnvList = envlist_init(envp);
   601    for (optind = 1; optind < double_dash;)
Target 0: (neomutt) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1000201f0)
  * frame #0: 0x00000001000201f0 neomutt`main(argc=1, argv=0x000000016fdfd730, envp=0x000000016fdfd740) at main.c:598:3
    frame #1: 0x0000000193dd60e0 dyld`start + 2360
```

**Comment by roccoblues** [comment]
sorry for closing, wrong button 🙈

**Comment by flatcap** [comment]
> error: ...

Thanks.  I should have spotted them sooner.
Fixed.

**Review by roccoblues — APPROVED** [review]
nice 👏🏼

**Pull request merged**
