### PR TITLE
Easy task: convert-regexlist-stailq

### PR DESCRIPTION
**Pull request by yuzibo**
This is my lastest version of the task,i do not want let it alone.

Signed-off-by: Bo YU <yuzibode@126.com>

* **What does this PR do?**
Convert regexlist to use stailq
* **Screenshots (if relevant)**

* **Does this PR meet the acceptance criteria?** (This is just a reminder for you,
  this section can be removed if you fulfill it.)

   - Documentation created/updated (you have to edit
     [doc/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/master/doc/manual.xml.head)
     for that)

   - All builds and tests are passing

   - Added [doxygen code documentation](https://neomutt.org/dev/doxygen)
     [syntax](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)

   - Code follows the [style guide](https://neomutt.org/dev/coding-style)

* **What are the relevant issue numbers?**
#1222

### CODE REVIEW

**Comment by flatcap** [comment]
Thanks for the updates, @yuzibo 

I've rebased your changes and added a few extra commits.
(I'll squash them down before merging).

- 02c3882d0 Convert RegexList to use STAILQ
  Your changes.  They look good.

- 2578c184e Fix the build for RegexList changes
  Some bits that didn't get converted

- ce68325ef Refactor RegexList changes
  Refactor a couple of functions to better use STAILQ, FOREACH

- 7f1bc2386 Convert ReplaceList to use STAILQ
  Change the ReplaceList too

I'll have another look through the code tomorrow (with fresh eyes), then merge it.

**Comment by gahr** [comment]
Hi - was any of this tested? The reason why I couldn't finish up testing the conversion of groups in #1187 was that I wasn't (and still am not) familiar enough with the concept, usage, and corner cases to be confident to put my name on any approval stamp.

However, I have a simple `group -group foers -rx ".*foo.*"` in my config file, which now segfaults starting at 4a0223 (bisected).

```
#0  0x00000000005400a2 in mutt_regexlist_add (rl=0x0, str=0x802ff8600 ".*foo.*", flags=2, err=0x7fffffffcab8) at mutt/regex.c:142
#1  0x0000000000442edf in group_add_regex (g=0x803032dc0, s=0x802ff8600 ".*foo.*", flags=2, err=0x7fffffffcab8) at group.c:188
#2  0x0000000000442e91 in mutt_group_context_add_regex (ctx=0x802e41880, s=0x802ff8600 ".*foo.*", flags=2, err=0x7fffffffcab8) at group.c:250
#3  0x0000000000451436 in parse_group (buf=0x7fffffffbd70, s=0x7fffffffb7d8, data=0, err=0x7fffffffcab8) at init.c:1169
#4  0x0000000000454fab in mutt_parse_rc_line (line=0x802e40400 "group -group fooers -rx \".*foo.*\"", token=0x7fffffffbd70, err=0x7fffffffcab8) at init.c:3197
#5  0x00000000004575cf in source_rc (rcfile_path=0x7fffffffbe00 "groups.cfg", err=0x7fffffffcab8) at init.c:852
#6  0x0000000000453305 in parse_source (buf=0x7fffffffc810, s=0x7fffffffc278, data=0, err=0x7fffffffcab8) at init.c:1877
#7  0x0000000000454fab in mutt_parse_rc_line (line=0x802e40300 "source groups.cfg", token=0x7fffffffc810, err=0x7fffffffcab8) at init.c:3197
#8  0x00000000004575cf in source_rc (rcfile_path=0x802eaa2f0 "/home/gahr/.config/neomutt/neomuttrc", err=0x7fffffffcab8) at init.c:852
#9  0x0000000000456c3b in mutt_init (skip_sys_rc=false, commands=0x7fffffffe530) at init.c:3076
#10 0x00000000004612ba in main (argc=1, argv=0x7fffffffea20, envp=0x7fffffffea30) at main.c:684
```

Note that `rl` is `NULL` at the first argument of `mutt_regexlist_add`. You cannot use `NULL` in this construct:

```c
142├>  STAILQ_FOREACH_FROM(np, rl, entries)
```

**Comment by yuzibo** [comment]
Hi,
You are right.
In group.h:
```c
struct Group
{
  struct Address *as;
  struct RegexList *rs;
  char *name;
};
```
If i  try initialize the STAILQ list  in here also,right?
But i will try it after several hours.

**Comment by flatcap** [comment]
Fixed in d1decc65c [devel/regexlist]
`struct Group` is the only place where `struct RegexList` is dynamically created.
I've changed `Group` to use an object rather than the pointer and intialised the `STAILQ`.

**Comment by yuzibo** [comment]
I think we would better to quote in comment

> Struct Group is the only place where struct RegexList is dynamically created and we must initialize it.

Nice to naiver.

**Pull request merged**
