### PR TITLE
test: add pattern compilation tests

### PR DESCRIPTION
**Pull request by melbit-naveennathan**
* **What does this PR do?**

Adds a couple of tests for pattern compilation.

This will ease transition to using SLIST/STAILQ to replace Pattern linked-list structures per #1224 .

### CODE REVIEW

**Comment by gahr** [comment]
We really want the test to just depend on the librarized part of neomutt. I don't think we want to build a test binary that's all neomutt except main. Can you please try and put the part you want to test in a library such as `mutt/`?

**Comment by melbit-naveennathan** [comment]
Per earlier discussion I've migrated the pattern testing into its own executable to reduce the pollution of unnecessary dependencies on existing testsuites.

**Comment by flatcap** [comment]
I've just pushed an updated version to branch [`devel/pattern_test`](https://github.com/neomutt/neomutt/tree/devel/pattern_test)
(I can't seem to update this PR -- there's a tickbox when you create it)

The new commit:
- Reverts the build changes requiring all of NeoMutt's objects
- Adds `extract.c` - a complete copy of `mutt_extract_token()` from `init.c`
- Adds `dummy.c` - empty functions to fulfill dependencies
- Builds against `pattern.c`

The dummy functions mean that many of the features of `mutt_extract_token()` won't work, but Pattern's dependencies are now much clearer.

**Comment by nnathan** [comment]
I've incorporated the changes and migrated tests for SLIST_* macros over. It is now living in https://github.com/neomutt/neomutt/tree/test/pattern . This won't get merged in until we can refactor so that it only uses the libraries per discussion with @gahr.

**Pull request closed without merging**
