### PR TITLE
Issue 888: Fix imap mailbox flag logging

### PR DESCRIPTION
**Pull request by lrosenman**
* **What does this PR do?**
   changes the imap mailbox flags logging to be more readable

* **Are there points in the code the reviewer needs to double check?**
   no

* **What are the relevant issue numbers?**
#888

### CODE REVIEW

**Comment by gahr** [comment]
How about storing all the flags in a nocely formatted temporary buffer and log them at once? The disadvantage would be an additional memory allocation, unless we want to chech for the debug level.

**Comment by flatcap** [comment]
One possibility is to use `struct Buffer` and `mutt_buffer_printf()` to generate the full string.

**Comment by gahr** [comment]
Yep that’s what I had in mind. Also, it should be possible to use a buffer on the stack to avoid the additional memory allocation.

**Comment by lrosenman** [comment]
I guess one question is how big to make the buffer since on a server that allows random flags (dovecot, et al), it could be a LONG list, see my pastebin.

**Comment by lrosenman** [comment]
And, it looks like it might not be that bad (and Buffer seems like it does the right thing to auto-expand).  I'm working on a patch :) which I will add to this PR.

**Comment by gahr** [comment]
I would personally prefer to keep a single log entry on a single line, no matter how long that might be. Would help with grepping etc.

**Comment by gahr** [comment]
The code looks good, thanks!

However, I test-ran it and saw how this formatting is different from the one specified by the IMAP protocol as a return from the `FLAGS` command or as untagged responses, e.g., when opening a mailbox.

```
6< * FLAGS (\Answered \Flagged \Deleted \Seen \Draft Old $Forwarded $MDNSent $NotJunk NonJunk $Junk Junk Unread)
...
6< * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft Old $Forwarded $MDNSent $NotJunk NonJunk $Junk Junk Unread \*)] Flags permitted.
...
Mailbox flags: [\Answered] [\Flagged] [\Deleted] [\Seen] [\Draft] [Old] [$Forwarded] [$MDNSent] [$NotJunk] [NonJunk] [$Junk] [Junk] [\*]
```
So, I have two questions:

1. Do we still want to print that log entry, given that the response was logged just above anyway?
2. If we do, do we want to wrap each flag inside square brackets? If we do, why?

**Comment by lrosenman** [comment]
The original code listed each flag with square brackets and as a separate log message (but without a new line, see the pastebin in #888). 

I think we do want to list the flags that we noticed as confirmation.

**Pull request merged**
