### PR TITLE
support sort_th for sub thread

### PR DESCRIPTION
**Pull request by fengidri**
* **What does this PR do?**
When sort = threads, then top threads and sub threads will sort by
sort_aux.

But, i want top threads sort by reverse-date, and the sub threads
under one thread sort by date. So I add sort_th to do this.

* **Screenshots (if relevant)**

* **Does this PR meet the acceptance criteria?** (This is just a reminder for you,
  this section can be removed if you fulfill it.)

   - Documentation created/updated (you have to edit
     [doc/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/master/doc/manual.xml.head)
     for that)

   - All builds and tests are passing

   - Added [doxygen code documentation](https://neomutt.org/dev/doxygen)
     [syntax](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)

   - Code follows the [style guide](https://neomutt.org/dev/coding-style)

* **What are the relevant issue numbers?**
#2342

### CODE REVIEW

**Comment by flatcap** [comment]
Thanks for the PR, @fengidri :heart: 

Over the years, a lot of ideas have been proposed to "fix the sorting".
One idea that I liked was a list of sort parameters, "thread,date,...".
The trouble is that nobody actually sat down and listed all the possible combinations.
(if you have time, that would be brilliant :-)

Your PR works and gives a little more control to the user. :tada:
 
But... it adds another config item.
Once we release NeoMutt with a new config item, it's hard to change our minds.

Let's see if anyone has thoughts.

Thanks again.

**Comment by flatcap** [comment]
**Note**: I've rebased your branch over the recent changes to master.

We've had a chance to play around, now, and we've found a bug.

When `sort=threads sort_aux=last-date-received`, the default setting for `sort_th` gives a different email order to unpatched-NeoMutt.

It can be clearly seen if you <kbd>Alt-V</kbd> to collapse all threads, then switch between `sort_th=date` and `sort_th=reverse-date`.
The top-level emails move around.

**Comment by BlackLotus** [comment]
Ok don't know if this is the correct way (to help the pull request and to solve the problem), but here I go.

> When sort=threads sort_aux=last-date-received, the default setting for sort_th gives a different email order to unpatched-NeoMutt.

If you want the default neomutt behavior to not to change at all the only way I see is to not use sort_th without being explicitly being set. 

I created a pull request against fengidri's repository with this branch https://github.com/BlackLotus/neomutt/tree/sort_th-fix
What it does is it sets the default value for sort_th to SORT_DUMMY and only executes the new method if it was changed. I probably implemented it wrong and/or misunderstood the actualy problem, but there it is.

**Comment by flatcap** [comment]
> Ok don't know if this is the correct way (to help the pull request and to solve the problem)

No it isn't, but don't worry about it :-)
It's just taken me 10 minutes of fiddling, but the correct solution would have been to open a Pull Request against @fengidri's repo.

Starting in your repo, https://github.com/BlackLotus/neomutt
- Select your branch (sort_th-fix): https://github.com/BlackLotus/neomutt/tree/sort_th-fix
- Hit the "Pull Request" button: https://github.com/neomutt/neomutt/compare/master...BlackLotus:sort_th-fix?expand=1
- You might need to click "compare across forks"
- Select the base repo (fengidri/neomutt) : https://github.com/fengidri/neomutt/compare/master...BlackLotus:sort_th-fix?expand=1
- Then fill in the details and hit "Create Pull Request"

It should look like this:
pr

That would create a Pull-Request stacked on top of @fengidri's, who could choose to merge it into their branch.

I'll have a look at your changes later.  If they're not crazy, I'll merge them into the PR, manually.

**Comment by BlackLotus** [comment]
I already did that (although I somehow selected the wrong repo _twice_ how is this even possible?).
Posted my comment here just to discuss the proposed solution.

**Comment by fengidri** [comment]
Sorry for making you wait so long.

I have an idea, we can make some modifications in the sort configuration, such as:

`set sort=reverse-date-sent.date
`
How do you feel about this method, so you don't need to add a new configuration item in config. @flatcap

**Comment by flatcap** [comment]
Sorry this is moving slowly.

Before I can merge this PR, I really need to understand the whole problem.
I don't want to find out, after a release, that I've broken a common use-case.

I've tried to think through all the possible combinations of `sort`, `sort_aux`,
but I simply don't have the time to give it my full attention.

What I'd like is a diagram of **every** possible sort combination.

This isn't as crazy as it sounds.

We'd need some sample Emails.
There'd be two sets of cases: flat, threaded.

The flat cases, we could have (say) up to three levels of sorting.
If the first level matches, try the second, then the third.
Documenting these should be pretty simple.

For the threaded cases, we'd want the same three levels, plus the keyword 'threads'.
These cases are more complicated because of the `last-` prefix.
The arrival of a new email can alter the parent's sort position.

```
01	Subject
02	├─>
03	│ └─>
04	└─>
05	  └─>
06	    └─>
07	      └─>
```

Starting with a sorted tree of emails, for each level of email,
we need to consider how a reply can change the sort order.

For the purposes of documentation, we don't need to know that _actual_ sort method.
So, sorting by subject, label, etc, can be considered as one sort method.
We just need to know that they're different:

```
set sort=meth1,meth2,meth3
```

If we can document all the possible cases, we can write **tests** for them.
That'd make me a very happy man :-)

This is quite a big job, but it's an important step to making NeoMutt reliable and predictable.

**Comment by flatcap** [comment]
Archived to https://github.com/neomutt/neomutt-old#neomutt-2021-02-05

**Pull request closed without merging**
