### PR TITLE
ncrypt/: Don't introduce spurious blank lines in protected blocks

### PR DESCRIPTION
**Pull request by alejandro-colomar**
These blank lines are not part of the signed and/or encrypted message. neomutt(1) was claiming so, which was incorrect.

Closes: <https://github.com/neomutt/neomutt/issues/4242>
Link: <https://github.com/neomutt/neomutt/pull/4221#issuecomment-2048251472>
Cc: @nabijaczleweli 

* **What does this PR do?**

Remove spurious blank lines in protected blocks.

* **Screenshots (if relevant)**

```
[-- Begin signature information --]
Good signature from: Alejandro Colomar <alx@alejandro-colomar.es>
                aka: Alejandro Colomar <alx@kernel.org>
                aka: Alejandro Colomar Andres <alx.manpages@gmail.com>
            created: Wed Apr 10 19:04:31 2024
[-- End signature information --]

[-- The following data is PGP/MIME signed and encrypted --]
Subject: REDACTED

Hi!

REDACTED

Have a lovely day!
Alex

--
<https://www.alejandro-colomar.es/>
[-- End of PGP/MIME signed and encrypted data --]
```

This is after the patch.  I won't paste again the before, as you already know it probably, and I already explained in the linked issue.

* **Does this PR meet the acceptance criteria?** (This is just a reminder for you,
  this section can be removed if you fulfill it.)

   - Documentation created/updated (you have to edit
     [docs/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/main/docs/manual.xml.head)
     for that)

      I hope we don't need docs.

   - All builds and tests are passing

      Builds and works $here.

   - Added [doxygen code documentation](https://neomutt.org/dev/doxygen)
     [syntax](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)

      N/ah.

   - Code follows the [style guide](https://neomutt.org/dev/code)

      Yep

* **What are the relevant issue numbers?**

    <https://github.com/neomutt/neomutt/issues/4242>

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
v1b changes:

-  Credit @nabijaczleweli for suggesting this (not exactly this, but yeah)

```
$ git range-diff main gh/blank blank 
1:  f86a065cc ! 1:  b7334b654 ncrypt/: Don't introduce spurious blank lines in protected blocks
    @@ Commit message
         These blank lines are not part of the signed and/or encrypted message.
         neomutt(1) was claiming so, which was incorrect.
     
    +    As наб complained in the link below, I think we were abusing blank lines
    +    a bit too much.
    +
         Closes: <https://github.com/neomutt/neomutt/issues/4242>
    +    Link: <https://github.com/neomutt/neomutt/issues/4242>
         Cc: наб <nabijaczleweli@nabijaczleweli.xyz>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
```

**Comment by alejandro-colomar** [comment]
v1c changes:

-  Paste the right link

```
$ git range-diff main gh/blank blank 
1:  705f8b0c7 ! 1:  484ac8b14 ncrypt/: Don't introduce spurious blank lines in protected blocks
    @@ Commit message
         a bit too much.
     
         Closes: <https://github.com/neomutt/neomutt/issues/4242>
    -    Link: <https://github.com/neomutt/neomutt/issues/4242>
    +    Link: <https://github.com/neomutt/neomutt/pull/4221#issuecomment-2048251472>
         Cc: наб <nabijaczleweli@nabijaczleweli.xyz>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
```

**Comment by gahr** [comment]
Probably a dumb question, but are we guaranteed that the markers start on a fresh line anyway?

**Comment by alejandro-colomar** [comment]
> Probably a dumb question, but are we guaranteed that the markers start on a fresh line anyway?

I think so.  I tried corrupting a message (removing the trailing blank line at the end of the MIME entity, before the MIME boundary) trying to make it not start in a new line and couldn't.  Even if the line is removed, neomutt(1) shows it fine.  The signature is made invalid, but it still renders the same.

But please, you're invited to prove me wrong, so please test.  The code has so many paths that I can't guarantee that there's not a path that doesn't have the blank.

**Comment by alejandro-colomar** [comment]
Oh well, I got out of the laziness.  Here's a blame of this.  Those blanks go all the way back to commit 0:

```
alx@debian:~/src/mutt/neomutt/main$ grep -Irl '"\[-- The following data is signed --]' | grep -v ^po | xargs git blame HEAD^ -- | grep '"\[-- The following data is signed --]'
b392cebb45 ncrypt/crypt.c (Richard Russon (@flatcap)                 2023-03-16 15:26:01 +0000 1241)       state_attach_puts(state, _("[-- The following data is signed --]\n\n"));
alx@debian:~/src/mutt/neomutt/main$ git show b392cebb45 | grep '^[+-].*"\[-- The following data is signed --]'
-      state_attach_puts(s, _("[-- The following data is signed --]\n\n"));
+      state_attach_puts(state, _("[-- The following data is signed --]\n\n"));
alx@debian:~/src/mutt/neomutt/main$ grep -Irl '"\[-- The following data is signed --]' | grep -v ^po | xargs git blame b392cebb45^ -- | grep '"\[-- The following data is signed --]'
af708f4fa9 ncrypt/crypt.c (Richard Russon (@flatcap)           2019-10-24 00:59:10 +0100 1227)       state_attach_puts(s, _("[-- The following data is signed --]\n\n"));
alx@debian:~/src/mutt/neomutt/main$ git show af708f4fa9 | grep '^[+-].*"\[-- The following data is signed --]'
-      state_attach_puts(_("[-- The following data is signed --]\n\n"), s);
+      state_attach_puts(s, _("[-- The following data is signed --]\n\n"));
alx@debian:~/src/mutt/neomutt/main$ grep -Irl '"\[-- The following data is signed --]' | grep -v ^po | xargs git blame af708f4fa9^ -- | grep '"\[-- The following data is signed --]'
41b5f7640f crypt.c        (Richard Russon (@flatcap)   2017-04-12 19:45:24 +0100 1239)       state_attach_puts(_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git show 41b5f7640f | grep '^[+-].*"\[-- The following data is signed --]'
-      state_attach_puts (_("[-- The following data is signed --]\n\n"), s);
+      state_attach_puts(_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ grep -Irl '"\[-- The following data is signed --]' | grep -v ^po | xargs git blame 41b5f7640f^ -- | grep '"\[-- The following data is signed --]'
fatal: no such path ncrypt/crypt.c in 41b5f7640f^
alx@debian:~/src/mutt/neomutt/main$ git blame 41b5f7640f^ -- crypt.c | grep '"\[-- The following data is signed --]'
49dea5cb67 (UPSTREAM Thomas Roessler        2002-01-24 21:53:19 +0000 1014)       state_attach_puts (_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git show 49dea5cb67 | grep '^[+-].*"\[-- The following data is signed --]'
+      state_attach_puts (_("[-- The following data is signed --]\n\n"), s);
-      state_attach_puts (_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git blame 49dea5cb67^ -- crypt.c | grep '"\[-- The following data is signed --]'
fatal: no such path crypt.c in 49dea5cb67^
alx@debian:~/src/mutt/neomutt/main$ git blame 49dea5cb67^ -- pgp.c | grep '"\[-- The following data is signed --]'
a4aa9bc2c5 (UPSTREAM Thomas Roessler 2001-11-08 10:55:55 +0000  847)       state_attach_puts (_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git show a4aa9bc2c5 | grep '^[+-].*"\[-- The following data is signed --]'
-      state_puts (_("[-- The following data is signed --]\n\n"), s);
+      state_attach_puts (_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git blame a4aa9bc2c5^ -- pgp.c | grep '"\[-- The following data is signed --]'
b423ebbfa9 (UPSTREAM Thomas Roessler 1999-01-04 13:16:20 +0000  839)       state_puts (_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git show b423ebbfa9 | grep '^[+-].*"\[-- The following data is signed --]'
+      state_puts (_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git show b423ebbfa9 | grep '^[+-].*"\[-- The following data is .*signed --]'
-      state_puts (_("[-- The following data is PGP/MIME signed --]\n\n"), s);
+      state_puts (_("[-- The following data is signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git blame b423ebbfa9^ -- pgp.c | grep '"\[-- The following data is .*signed --]'
3131a49fe1 (UPSTREAM Thomas Roessler 1998-10-01 09:27:57 +0000  677)       state_puts (_("[-- The following data is PGP/MIME signed --]\n\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git show 3131a49fe1 | grep '^[+-].*"\[-- The following data is .*signed --]'
-      state_puts ("[-- The following data is PGP/MIME signed --]\n\n", s);
+      state_puts (_("[-- The following data is PGP/MIME signed --]\n\n"), s);
+"[-- The following data is PGP/MIME signed --]\n"
+"[-- The following data is PGP/MIME signed --]\n"
alx@debian:~/src/mutt/neomutt/main$ git blame 3131a49fe1^ -- pgp.c | grep '"\[-- The following data is .*signed --]'
^1a5381e07 (UPSTREAM Thomas Roessler 1998-06-08 09:16:03 +0000  676)       state_puts ("[-- The following data is PGP/MIME signed --]\n\n", s);
alx@debian:~/src/mutt/neomutt/main$ git show 1a5381e07 | grep '^[+-].*"\[-- The following data is .*signed --]'
+      state_puts ("[-- The following data is PGP/MIME signed --]\n\n", s);
alx@debian:~/src/mutt/neomutt/main$ git show 1a5381e07 | grep '^[+-].*\[-- End of .*signed data --]'
+      state_puts ("\n[-- End of PGP/MIME signed data --]\n", s);
```

And the signature information block:

```
alx@debian:~/src/mutt/neomutt/main$ grep -Irl '"\[-- Begin signature information --]' | grep -v ^po | xargs git blame HEAD^ -- | grep '"\[-- Begin signature information --]'
b392cebb45 ncrypt/crypt_gpgme.c (Richard Russon (@flatcap)                 2023-03-16 15:26:01 +0000 1569)   state_attach_puts(state, _("[-- Begin signature information --]\n"));
b392cebb45 ncrypt/crypt_gpgme.c (Richard Russon (@flatcap)                 2023-03-16 15:26:01 +0000 1802)       state_attach_puts(state, _("[-- Begin signature information --]\n"));
b392cebb45 ncrypt/crypt_gpgme.c (Richard Russon (@flatcap)                 2023-03-16 15:26:01 +0000 2612)             state_attach_puts(state, _("[-- Begin signature information --]\n"));
alx@debian:~/src/mutt/neomutt/main$ git show b392cebb45 | grep '^[+-].*"\[-- Begin signature information --]'
-  state_attach_puts(s, _("[-- Begin signature information --]\n"));
+  state_attach_puts(state, _("[-- Begin signature information --]\n"));
-      state_attach_puts(s, _("[-- Begin signature information --]\n"));
+      state_attach_puts(state, _("[-- Begin signature information --]\n"));
-            state_attach_puts(s, _("[-- Begin signature information --]\n"));
+            state_attach_puts(state, _("[-- Begin signature information --]\n"));
alx@debian:~/src/mutt/neomutt/main$ grep -Irl '"\[-- Begin signature information --]' | grep -v ^po | xargs git blame b392cebb45^ -- | grep '"\[-- Begin signature information --]'
af708f4fa9 ncrypt/crypt_gpgme.c (Richard Russon (@flatcap)        2019-10-24 00:59:10 +0100 1560)   state_attach_puts(s, _("[-- Begin signature information --]\n"));
af708f4fa9 ncrypt/crypt_gpgme.c (Richard Russon (@flatcap)        2019-10-24 00:59:10 +0100 1792)       state_attach_puts(s, _("[-- Begin signature information --]\n"));
af708f4fa9 ncrypt/crypt_gpgme.c (Richard Russon (@flatcap)        2019-10-24 00:59:10 +0100 2542)             state_attach_puts(s, _("[-- Begin signature information --]\n"));
alx@debian:~/src/mutt/neomutt/main$ git show af708f4fa9 | grep '^[+-].*"\[-- Begin signature information --]'
-  state_attach_puts(_("[-- Begin signature information --]\n"), s);
+  state_attach_puts(s, _("[-- Begin signature information --]\n"));
+      state_attach_puts(s, _("[-- Begin signature information --]\n"));
+            state_attach_puts(s, _("[-- Begin signature information --]\n"));
alx@debian:~/src/mutt/neomutt/main$ grep -Irl '"\[-- Begin signature information --]' | grep -v ^po | xargs git blame af708f4fa9^ -- | grep '"\[-- Begin signature information --]'
41b5f7640f crypt_gpgme.c        (Richard Russon (@flatcap)         2017-04-12 19:45:24 +0100 2071)   state_attach_puts(_("[-- Begin signature information --]\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git show 41b5f7640f | grep '^[+-].*"\[-- Begin signature information --]'
-  state_attach_puts (_("[-- Begin signature information --]\n"), s);
+  state_attach_puts(_("[-- Begin signature information --]\n"), s);
alx@debian:~/src/mutt/neomutt/main$ grep -Irl '"\[-- Begin signature information --]' | grep -v ^po | xargs git blame 41b5f7640f^ -- | grep '"\[-- Begin signature information --]'
fatal: no such path ncrypt/crypt_gpgme.c in 41b5f7640f^
alx@debian:~/src/mutt/neomutt/main$ git blame 41b5f7640f^ -- crypt_gpgme.c | grep '"\[-- Begin signature information --]'
1afaa74a19 crypt-gpgme.c (UPSTREAM Werner Koch       2005-01-28 13:17:22 +0000 1558)   state_attach_puts (_("[-- Begin signature information --]\n"), s);
alx@debian:~/src/mutt/neomutt/main$ git show 1afaa74a19 | grep '^[+-].*"\[-- Begin signature information --]'
+  state_attach_puts (_("[-- Begin signature information --]\n"), s);
```

So they were indeed developed at very different times, and by different people.  And the blanks I'm removing were there probably for symmetry only.

**Comment by alejandro-colomar** [comment]
@flatcap Please retarget to <https://github.com/neomutt/neomutt/tree/devel/security>.

**Comment by alejandro-colomar** [comment]
v1d changes:

-  Extensively clarify in the commit message the reasons for this.

```
$ git range-diff main gh/blank blank 
1:  484ac8b14 ! 1:  37d2cfd1d ncrypt/: Don't introduce spurious blank lines in protected blocks
    @@ Metadata
      ## Commit message ##
         ncrypt/: Don't introduce spurious blank lines in protected blocks
     
    +    TL;DR:
    +
         These blank lines are not part of the signed and/or encrypted message.
         neomutt(1) was claiming so, which was incorrect.
     
    -    As наб suggested in the link below, I think we were abusing blank lines
    +    As наб suggested (see links below), I think we were abusing blank lines
         a bit too much.
     
    +    Long story:
    +
    +    A MIME part doesn't include the trailing blank line.  That blank line
    +    belongs to the structure of the whole message, and doesn't belong to the
    +    body part.
    +
    +    A typical PGP/MIME email looks like this:
    +
    +            Date: Mon, 1 Apr 2024 21:40:04 +0200
    +            From: Alejandro Colomar <alx@alejandro-colomar.es>
    +            To: spam@alejandro-colomar.es
    +            Subject: After
    +            Message-ID: <ZgsNlP1MtLAsGBA3@debian>
    +            MIME-Version: 1.0
    +            Content-Type: multipart/signed; micalg=pgp-sha512;
    +                    protocol="application/pgp-signature"; boundary="bHQR9+uNWFqbSKv/"
    +            Content-Disposition: inline
    +
    +            --bHQR9+uNWFqbSKv/
    +            Content-Type: text/plain; protected-headers=v1; charset=utf-8
    +            Content-Disposition: inline
    +            Date: Mon, 1 Apr 2024 21:40:04 +0200
    +            From: Alejandro Colomar <alx@alejandro-colomar.es>
    +            To: spam@alejandro-colomar.es
    +            Subject: After
    +
    +            Supposedly, migadu is fixed now.  Let's see
    +
    +            --bHQR9+uNWFqbSKv/
    +            Content-Type: application/pgp-signature; name="signature.asc"
    +
    +            -----BEGIN PGP SIGNATURE-----
    +
    +            iQIzBAABCgAdFiEE6jqH8KTroDDkXfJAnowa+77/2zIFAmYLDZQACgkQnowa+77/
    +            2zKXvBAApT2XkOxpPRRmhjawh/axbHG3NXBldiYe9DAupE4eVJLxLnv8/tf+WWHU
    +            oru0vdOBaO1H8VwNi22P+aXo+29HARKawlwhVmgd2auSYzrR+UaSTSwLTN0UO8e/
    +            KCG2LHPMrTnZjPmlWdVRjOq44hkwes32yByjGrVz6cuwtss7XAdDmxuRGpRjHB47
    +            EVBstReybfepSXEhPJTB+yUfUpnVZ9G4nUBDlBODHHY8T2FPB8AMQmXAUGSIn96Y
    +            V33lIyiQ92gBrp3UmppfegOU+Clt18UD9tGs00UmIRlagclS9gUcUrY8CeKKMOJ5
    +            PYjsyqjiBLTVO58lKAjXEcAOMs0us+psxmSgzqBw52bLhxlwUDytwMUJUcQiERme
    +            zG6lz2lbZ45PMzrtKcm4fAxoJyQgwyf5zrQG5iyqvkmngQoo3ONlqZsZPz9GQffi
    +            C6uB8lmRvJM4FcPs/w2Ee6bXA3xk9ClGWryFGwdJM49nGMPXyzDx3/nc5KlOAXAn
    +            QPqFSy+kEuzXGJXQZcYwj0o/xNU3B+EecZH148xuAzBHpk8yQd07ZOGhwJFnUq+N
    +            r/cr0pr4A74t+J38Bb4vLKcWgg2pqISqX6zf/0VyYEa6o7dvMxG31gRw+z/Tv+Ln
    +            2WKY/wWvJHbfFuhED7uNtMfiKq8JA2ZxyKi9z/V5G780/89soG0=
    +            =BrzD
    +            -----END PGP SIGNATURE-----
    +
    +            --bHQR9+uNWFqbSKv/--
    +
    +    Of which the main body part is precisely this:
    +
    +            ```
    +            Content-Type: text/plain; protected-headers=v1; charset=utf-8
    +            Content-Disposition: inline
    +            Date: Mon, 1 Apr 2024 21:40:04 +0200
    +            From: Alejandro Colomar <alx@alejandro-colomar.es>
    +            To: spam@alejandro-colomar.es
    +            Subject: After
    +
    +            Supposedly, migadu is fixed now.  Let's see
    +            ```
    +
    +    Note no trailing blank.  When verifying the signature, that blank line
    +    belongs to the encapsulation boundary, and if included, it would fail
    +    the verification.  See <https://github.com/neomutt/neomutt/issues/4229>
    +    for that.
    +
    +    Then, a MIME part can be further subdivided.
    +
    +    Quoting RFC1521:
    +    > Each part starts with an encapsulation boundary, and then contains a
    +    > body part consisting of header area, a blank line, and a body area.
    +
    +    This RFC has been obsoleted by RFC2045, but the new one is less clear in
    +    the wording, and probably nothing really changed, so don't worry about
    +    it.
    +
    +    This says that the blank line between the headers and the body is
    +    *not* part of the body.  This is very much like with HTTP messages.
    +
    +    [neo]mutt(1), however, when displaying signed/encrypted email, printed
    +    both the separating blank and the trailing blank (or it invented a blank
    +    line before and after the body, however it is; it might be that, since
    +    the blank goes even before the protected subject, if there is one).
    +    These blanks were spurious, and may lead to think that the original body
    +    actually has those blanks.  That's a lie.  Not a big one, but a lie.
    +
    +    Trimming those 2 blanks makes the output more correct, faithful to the
    +    original message as it was sent, and less consuming of non-renovable
    +    resources (think of 24-rows here).
    +
         Closes: <https://github.com/neomutt/neomutt/issues/4242>
         Link: <https://github.com/neomutt/neomutt/pull/4221#issuecomment-2048251472>
    +    Link: <https://github.com/neomutt/neomutt/issues/4229>
    +    Link: <https://datatracker.ietf.org/doc/html/rfc1521#section-7.2>
    +    Link: <https://datatracker.ietf.org/doc/html/rfc2045#section-2.4>
         Cc: наб <nabijaczleweli@nabijaczleweli.xyz>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
```

**Comment by alejandro-colomar** [comment]
v1e changes:

-  Fix spelling of renewable.
-  Cc @gahr 

```
$ git range-diff main gh/blank blank 
1:  37d2cfd1d ! 1:  f41712317 ncrypt/: Don't introduce spurious blank lines in protected blocks
    @@ Commit message
         actually has those blanks.  That's a lie.  Not a big one, but a lie.
     
         Trimming those 2 blanks makes the output more correct, faithful to the
    -    original message as it was sent, and less consuming of non-renovable
    +    original message as it was sent, and less consuming of non-renewable
         resources (think of 24-rows here).
     
         Closes: <https://github.com/neomutt/neomutt/issues/4242>
    @@ Commit message
         Link: <https://datatracker.ietf.org/doc/html/rfc1521#section-7.2>
         Link: <https://datatracker.ietf.org/doc/html/rfc2045#section-2.4>
         Cc: наб <nabijaczleweli@nabijaczleweli.xyz>
    +    Cc: Pietro Cerutti <gahr@gahr.ch>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
      ## ncrypt/crypt.c ##
```

**Comment by alejandro-colomar** [comment]
v2 changes:

-  I had missed another instance of this.

```
$ git range-diff neomutt/main gh/blank blank 
1:  f41712317 ! 1:  6d5fc874a ncrypt/: Don't introduce spurious blank lines in protected blocks
    @@ ncrypt/crypt_gpgme.c: int smime_gpgme_application_handler(struct Body *b, struct
                                                 _("[-- End of S/MIME encrypted data --]\n"));
          }
     
    + ## ncrypt/pgp.c ##
    +@@ ncrypt/pgp.c: int pgp_class_encrypted_handler(struct Body *b, struct State *state)
    +   {
    +     if (state->flags & STATE_DISPLAY)
    +     {
    +-      state_attach_puts(state, _("[-- The following data is PGP/MIME encrypted --]\n\n"));
    ++      state_attach_puts(state, _("[-- The following data is PGP/MIME encrypted --]\n"));
    +       mutt_protected_headers_handler(tattach, state);
    +     }
    + 
    +@@ ncrypt/pgp.c: int pgp_class_encrypted_handler(struct Body *b, struct State *state)
    + 
    +     if (state->flags & STATE_DISPLAY)
    +     {
    +-      state_puts(state, "\n");
    +       state_attach_puts(state, _("[-- End of PGP/MIME encrypted data --]\n"));
    +     }
    + 
    +
      ## ncrypt/smime.c ##
     @@ ncrypt/smime.c: static struct Body *smime_handle_entity(struct Body *b, struct State *state, FIL
        if (state->flags & STATE_DISPLAY)
```

**Comment by alejandro-colomar** [comment]
v2b changes:

-  Remove unnecessary braces

```
$ git range-diff neomutt/main gh/blank blank 
1:  6d5fc874a ! 1:  845d73d88 ncrypt/: Don't introduce spurious blank lines in protected blocks
    @@ ncrypt/pgp.c: int pgp_class_encrypted_handler(struct Body *b, struct State *stat
          }
      
     @@ ncrypt/pgp.c: int pgp_class_encrypted_handler(struct Body *b, struct State *state)
    +       b->goodsig |= tattach->goodsig;
      
          if (state->flags & STATE_DISPLAY)
    -     {
    +-    {
     -      state_puts(state, "\n");
            state_attach_puts(state, _("[-- End of PGP/MIME encrypted data --]\n"));
    -     }
    +-    }
      
    +     mutt_body_free(&tattach);
    +     /* clear 'Invoking...' message, since there's no error */
     
      ## ncrypt/smime.c ##
     @@ ncrypt/smime.c: static struct Body *smime_handle_entity(struct Body *b, struct State *state, FIL
```

**Comment by alejandro-colomar** [comment]
v2c (by @flatcap ) changes:

-  Rebase on devel/security

```
$ git range-diff devel/security..blank neomutt/devel/security..gh/blank
1:  845d73d88 = 1:  b6c6e0859 ncrypt/: Don't introduce spurious blank lines in protected blocks
```

**Comment by alejandro-colomar** [comment]
Thanks!

FTR:

```
$ git range-diff b6c6e0859^..b6c6e0859 048902b^^..048902b
1:  b6c6e0859 = 1:  559db2855 ncrypt/: Don't introduce spurious blank lines in protected blocks
-:  --------- > 2:  048902b85 update translations for blank lines
```

**Comment by alejandro-colomar** [comment]
Cc: @gahr , @nabijaczleweli , @flatcap 

> > Probably a dumb question,
> 
> Legitimate question, IMO.
> 
> > but are we guaranteed that the markers start on a fresh line anyway?
> 
> I _think_ so. I tried corrupting a message (removing the trailing blank line at the end of the MIME entity, before the MIME boundary) trying to make it not start in a new line and couldn't. Even if the line is removed, neomutt(1) shows it fine. The signature is made invalid, but it still renders the same.

Back then, I didn't think of the possibility of corrupting a base64-encoded message.  Maybe that could mess with the MIME part.  I'm not sure though.  I know that in the PGP encrypted data it's possible.

I've tried this:

```
$ printf "data\ndata\ndata" | gpg --encrypt-to alx@kernel.org --encrypt-to 'наб <nabijaczleweli@nabijaczleweli.xyz>' --armor --encrypt > no_trail_nl.asc
```

And it certainly misbehaves.  However, we're lucky that I forgot to patch the `BEGIN PGP MESSAGE` stuff.

Now, I wonder if base64 is a way to manage the MIME parts to misbehave similarly.  I don't know.  I'll try to break it.  Please try yourself too, in case I don't find a way but there is.

> 
> But please, you're invited to prove me wrong, so please test. The code has so many paths that I can't guarantee that there's not a path that doesn't have the blank.

**Comment by alejandro-colomar** [comment]
Nah, even manually creating a mail in base64 encoding without a trailing NL, neomutt(1) shows it with a newline, so it behaves correctly.  I ignore how this happens internally, but I don't seem to be able to make neomutt(1) misbehave with a bad email.  Still, please try to pervert it, in case I'm not imaginative enough.

**Pull request merged**
