### PR TITLE
Convert pgpsignature to use stailq

### PR DESCRIPTION
**Pull request by yuzibo**
Signed-off-by: Bo YU <yuzibode@126.com>

* **What does this PR do?**
Convert pgpsignature to use stailq
* **Screenshots (if relevant)**

* **Does this PR meet the acceptance criteria?** (This is just a reminder for you,
  this section can be removed if you fulfill it.)

   - Documentation created/updated (you have to edit
     [doc/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/master/doc/manual.xml.head)
     for that)

   - All builds and tests are passing

   - Added [doxygen code documentation](https://neomutt.org/dev/doxygen)
     [syntax](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)

   - Code follows the [style guide](https://neomutt.org/dev/coding-style)

* **What are the relevant issue numbers?**
#1223

### CODE REVIEW

**Comment by yuzibo** [comment]
Ready for review too :)

**Comment by flatcap** [comment]
I've had a look and a think and I've decided on a change of plan.
SORRY!

The `PgpSignature` is only used by the `pgpring` tool.
The `pgpring` tool is only needed by users of PGP2 and PGP5.
PGP5 is over twenty years old.

New plan.  Kill the lot.  Please can you:
- remove `PgpSignature` from `ncrypt/pgplib.[ch]`
- remove `pgppubring.c`
- update `Makefile.autosetup`
- remove `contrib/pgp2.rc`
- remove `contrib/pgp5.rc`
- remove `contrib/pgp6.rc`
- update `contrib/Makefile.autosetup`

Thanks (and sorry, again).

**Comment by yuzibo** [comment]
Hello,
Comparing with modify code, i am glad to delete code :)
No problem.I will look into it.

**Comment by flatcap** [comment]
This has been closed and replaced by: Remove pgpsignature #1239

**Pull request closed without merging**
