### PR TITLE
Switch to using an external gettext runtime

### PR DESCRIPTION
**Pull request by gahr**
This PR allows us to get rid of the `intl` directory that used to keep an old version of the `gettext` implementation. The former approach is changed into using whatever `gettext` is installed in the system.

Generated `m4` files have been removed and added to `.gitignore`.

No code changes have been introduced. Please just check your build workflow :)

Issue: #460

### CODE REVIEW

**Comment by gahr** [comment]
@neomutt/reviewers please review

**Comment by gahr** [comment]
You can start reviewing, but I have to sort out a problem with `--disable-iconv`. Perhaps it makes sense not to have it altogether. See also what's written in `INSTALL`.

**Comment by gahr** [comment]
7004f96 removes support for building neomutt without iconv support. Please comment.

**Comment by gahr** [comment]
Rebased

**Comment by flatcap** [comment]
@gahr I've made one slight change -- I've reinstated `m4/funcs.m4` (temporarily).

In `configure.ac` there's a command `XIPH_FUNC_VA_COPY` (which I'd never seen before) which checks for the presence of `va_copy` which is part of C99.  Without that custom M4, I get warnings during configure.

I _think_ we're probably safe to delete both, but I'll wait 'til you're back.

**Pull request merged**
