### PR TITLE
help: Add message flags.

### PR DESCRIPTION
**Pull request by g0mb4**
Add explanation of message flags to the help screen of index.

### CODE REVIEW

**Comment by g0mb4** [comment]
Dear @flatcap ! 

Wow! Thank you for the very detailed help! I'll try to implement it.

**Comment by g0mb4** [comment]
:D thanks for the image

**Review by flatcap — CHANGES_REQUESTED** [review]
The code looks good.
There's only one thing that isn't great and that's not your fault.
It's hard to line up a character on the left with the text on the right.

Please can you insert a label for each of the three blocks, e.g.
```c
format_line(fp, 0, "$to_chars", "", "", wraplen);
```

Thanks!

**Comment by g0mb4** [comment]
Thanks! Yup, I think maybe an alternating background color would help, but that is an other PR. Sure, I'll insert the labels.

**Review by flatcap — APPROVED** [review]
Lovely job.  Thanks!

**Comment by flatcap** [comment]
> I think maybe an alternating background color would help

Yes.  It's been discussed before but nobody's quite got around to it.

> but that is an other PR

Yes please :-)

Perhaps a [quick discussion](https://github.com/neomutt/neomutt/discussions/categories/development) first...
Do we want it for just the help, or would other dialogs benefit?
Should it be configurable?
Work out some implemtation details (help available, of course)

The other thing I thought of, if you're interested, was creating an enum for these ugly constants.
They're not used in many places.

https://github.com/g0mb4/neomutt/blob/e42431f4d0563a691e648ccf5862727695637156/help.c#L445-L453

Thanks

**Comment by asdf8dfafjk** [comment]
I came to this pull request searching googling "emojis to_chars neomutt" so for posterity: here's a (totally uncool) to_chars. This takes a bit to get hang of but after a while there is less mental effort than recollecting initials. (this is a guess, I can't actually get this to work yet lol)


set to_chars    = "🍌🥭🍉🍅🍪🍇🥥"

# Mnenomic

Banana has no seeds (=you're not a recepient), 

mango has just one (=you)

water melon has lots (you're one of many)

tomato stands for CC here

cookie means you cooked the mail

Grapes stands for mailing list 

Coconut is you are in reply-to




Also 

set flag_chars  = "🏷️❗🗑️🚮↩🙈🆕🙉🆕📜📜"

**Pull request merged**
