### PR TITLE
add 'prompt_user' command

### PR DESCRIPTION
**Pull request by motorto**
Implements the prompt_user command as discussed on #2659

### CODE REVIEW

**Comment by motorto** [comment]
@flatcap  , didn't die , just not having a lot of time to work on this , hopping that this weekend I get time to work on it !

**Comment by flatcap** [comment]
no worries. thanks for letting me know.

**Comment by flatcap** [comment]
ping?

**Comment by flatcap** [comment]
Archived to https://github.com/neomutt/neomutt-old#neomutt-2021-02-05

**Pull request closed without merging**
