### PR TITLE
add libcompose

### PR DESCRIPTION
**Pull request by matthewhughes934**
* **What does this PR do?**

Creates libcompose, moving `compose.{c,h}` code under `compose/`. It also moves compose specific compose code out of `mutt_config.c` into `compose/config.c`. The approach follows what was used for libsidebar (c.f. 9b348be)

* **What are the relevant issue numbers?**

#2622

### CODE REVIEW

**Comment by flatcap** [comment]
It's a good start, but...
I get linker errors:
```
/usr/bin/ld: libcompose.a(compose.o):(.bss+0x0): multiple definition of `C_ComposeFormat'; libcompose.a(config.o):(.bss+0x0): first defined here
/usr/bin/ld: libcompose.a(compose.o):(.bss+0x8): multiple definition of `C_Ispell'; libcompose.a(config.o):(.bss+0x8): first defined here
/usr/bin/ld: libcompose.a(compose.o):(.bss+0x10): multiple definition of `C_Postpone'; libcompose.a(config.o):(.bss+0x10): first defined here
/usr/bin/ld: libcompose.a(compose.o):(.bss+0x11): multiple definition of `C_ComposeShowUserHeaders'; libcompose.a(config.o):(.bss+0x11): first defined here
```

Also, I think you've missed out two other _Compose-only_ config variables.

**Comment by matthewhughes934** [comment]
> I get linker errors:

Hmmm, sorry about that. Not sure why it managed to link on my machine (I'd rather it didn't...), will have a look into it for my own sake.

This should be fixed with a051db4

> Also, I think you've missed out two other Compose-only config variables.

Whoops, will have a look into it

**Comment by matthewhughes934** [comment]
> Also, I think you've missed out two other Compose-only config variables.

My grepping has found candidates:

* `C_Copy`
* `C_EditHeaders`

Were these the two you were referring to?

**Comment by flatcap** [comment]
> Were these the two you were referring to?

yep :-)

**Comment by matthewhughes934** [comment]
Great, added with cdc83ff. I also decide to sort things as a matter of
tidying with 48ee90a.

**Review by flatcap — APPROVED** [review]

**Pull request merged**
