### PR TITLE
Do not crash when closing a non-opened mailbox

### PR DESCRIPTION
**Pull request by gahr**
Issue: #342

### CODE REVIEW

**Comment by d-k-c** [comment]
Your fix is okay for now, but as you said in your issue the problem is in the logic: why is `close` called when `open` fails afterall? But this logic issue is way larger than the issue you intend to fix, so let's leave it for later.

**Comment by riesebie** [comment]
Hi gents,

* Damien R. <notifications@github.com> [2017-01-30 08:11 -0800]:

> d-k-c approved this pull request.

* guiniol <notifications@github.com> [2017-01-30 09:48 -0800]:

> guiniol approved this pull request.
> 
> Looks good to me.

Why don't we manage those approvals by git? Just sign off the
patches. It would be good to manage patches in neomutt-devel as
well, or only?. We are working on a MUA and __not__ via unthreaded
and quite some non reproducible "issues" provided by a GitHub server
located in Trump-Land....

That are my thoughts for now ;-)

Elimar, who is a bit conservative on some circumstances, hehehehe.
-- 
  Numeric stability is probably not all that
  important when you're guessing;-)

**Comment by flatcap** [comment]
> Why don't we manage those approvals by git? Just sign off the patches. 

It's a nice thought, to have the reviewers remembered.
However, it would mean two extra commits for every pull-request.
(unless you force the update, causing problems for others).

**Comment by gahr** [comment]
As long as the issue is mentioned in the commit message, we'll be able to get back to the issue that resulted in the commit.

**Pull request closed without merging**
