### PR TITLE
help: fix search highlight

### PR DESCRIPTION
**Pull request by flatcap**
The recent change (73d873e42) to add striped highlighting had an unfortunate side-effect.
It masked the search highlighting, which is kinda useful in the help :-)

Here's what the fixed help looks like, with a variety of config settings:

image

**Config**:
```
color stripe_even default default                      color stripe_even underline default default
color stripe_odd  magenta yellow                       color stripe_odd  underline default default

color stripe_even white color234                       color stripe_even underline default default
color stripe_odd  white black                          color stripe_odd            default default

color stripe_even default color234                     color stripe_even bold default default
color stripe_odd  default default                      color stripe_odd       default default

color stripe_even default default                      color stripe_even cyan    red
color stripe_odd  default default                      color stripe_odd  magenta yellow
       
```

### CODE REVIEW

**Comment by roccoblues** [comment]
I can confirm that the search term is highlighted. But for me it's some bright yellow that makes it hard to read. Might be some terminal setting issue, don't let that block your from merging.

Screenshot 2023-08-26 at 17 28 27

**Comment by flatcap** [comment]
Thanks.

Hmm...  I don't like the look of the lines where the match is at the end of the line.

**Comment by roccoblues** [comment]
Out of curiosity: how/where is the highlight background color picked? I didn't find a setting for it.

**Comment by flatcap** [comment]
`color search [attrs] fg bg`

**Comment by roccoblues** [comment]
Screenshot 2023-08-26 at 17 58 21

Ok the color was just my weird setting. Looks good now! 👍🏼

**Review by roccoblues — APPROVED** [review]

**Pull request merged**
