### PR TITLE
allow source command to load multiple files at once

### PR DESCRIPTION
**Pull request by toogley**
* **What does this PR do?**
     allows the `source` command to take multiple arguments.

* **What are the relevant issue numbers?**
Issue #616

### CODE REVIEW

**Comment by toogley** [comment]
@neomutt/reviewers please review

**Comment by guyzmo** [comment]
I don't think this is really a good idea to include this patch, because having multiple source files in a single line is not much added value.

And it's encouraging the use of the following pattern: `source `echo ~/.mutt/*``.

It might be a better idea to have a special parsing of the file path to support the globbing, and include multiple files without shell expansion. Also Lua scripting could leverage that.

**Comment by gahr** [comment]
While I don't mind the feature per se - I could see a use for that - I would still fail early and stop sourcing at the first error.

**Comment by flatcap** [comment]
I agree with @gahr, it's reasonable and it should fail on the first error.
After all, mutt thinks this config line is OK:
```
set help sidebar_visible sidebar_width = 10 pager_index_lines = 5
```

**Comment by toogley** [comment]
@gahr i addressed your complaints, it works perfectly.

**Comment by flatcap** [comment]
Please limit the clang-format to just your changes (where possible).
I'll sort out the remainder before a release.

**Comment by toogley** [comment]
fixed.

**Comment by gahr** [comment]
... at which point `rc` is not needed and you simply return 0 after the loop ;)

**Comment by toogley** [comment]
@fixed ah, thanks. fixed.

**Comment by gahr** [comment]
Rebased onto master

**Comment by gahr** [comment]
I have tested this branch it works fine.

Perhaps a minor modification would be to turn the`do { ... } while (MoreArgs(token));` into a `while (MoreArgs(token)) { ... }`.

The only difference is that a line with `source` alone in a config file would simply be skipped instead of being reported like this:
```
Error in /home/gahr/.mutt/muttrc, line 169: source: file  could not be sourced. 
```

What do people think?

**Comment by flatcap** [comment]
hehe, I like the "cleanliness" of it, but...
I think I'd stick with `source<enter>` as an error.

**Comment by gahr** [comment]
fair enough :)

**Comment by flatcap** [comment]
I made one slight tweak to the docs to show optional multiple parameters:
```diff
       <para>Usage:</para>
       <cmdsynopsis>
         <command>source</command>
-        <arg choice="plain">
-          <replaceable class="parameter">file1</replaceable>
-          <replaceable class="parameter">file2</replaceable>
+        <arg choice="plain" rep="repeat">
+          <replaceable class="parameter">file</replaceable>
         </arg>
       </cmdsynopsis>
       <para>This command allows the inclusion of initialization commands from
```

**Pull request merged**
