### PR TITLE
Avoid browing the remote spoolfile by setting MUTT_SELECT_MULTI attach

### LINKED ISSUE #336: Query: Attach file
This bug was reported by Andrew Duchowski (on the neomutt-users mailing list).

On a Mac, I just changed from mutt to neomutt via
upgrades to macOS Sierra and macports.

In mutt, when I used to 'a'ttach a file and then
press '?' to search the list of folders, two things
happened:

1. I would see my ~/Mail foler
2. mutt would remember which dir I was in if I
   wanted to 'a'ttach again

Now, in neomutt, when I 'a'ttach a file, two
things happen:

1. I see my remote mail spoolfile (e.g., exchange)
   and now I have to press '=' to get to my local
   ~/Mail dir
2. neumutt no longer remembers where I was looking
   at for attachments, consequently I have to press
   '=' again and then descend down a possibly long
   directory branch to get to where I was just a
   second ago.

Is there a .muttrc switch to revert back to the
old functionality?

### PR DESCRIPTION
**Pull request by gahr**
Closes #336

### CODE REVIEW

**Comment by gahr** [comment]
@neomutt/reviewers Please review. This Works For Me (tm) but I'm not 100% confident that it doesn't fallout in some strange ways.
@P-EB I'd like to have your opinion on this, too.

**Comment by gahr** [comment]
@flatcap why was this closed?

**Comment by flatcap** [comment]
Hmm... Sorry, I don't know how I caused that (if I caused it).
A couple of branches have become "closed".
#TheGhostDidIt

**Comment by flatcap** [comment]
Ah, I think I know what it is.  I deleted [neomutt] and these two must have been branched from it.

**Comment by gahr** [comment]
Oh, alright, I was frightened :) no worries, I'll rebase this on top of master tomorrow!

**Comment by flatcap** [comment]
Open sesame!

**Comment by flatcap** [comment]
👍 Review: good :-)

**Comment by gahr** [comment]
trying as hard as I can to reopen this

**Pull request closed without merging**
