### PR TITLE
S/MIME contrib fixes

### PR DESCRIPTION
**Pull request by l2dy**
* **What does this PR do?**
Remove contrib/ca-bundle.crt and update S/MIME notes and test.
* **Are there points in the code the reviewer needs to double check?**
I've only tested smime_keys_test.pl on macOS with OpenSSL 1.0.2k.
* **Why was this PR needed?**
contrib/ca-bundle.crt is outdated and list of CAs is often provided by the system.
www.thawte.com no longer provides free S/MIME certificates.
www.verisignlabs.com/Projects/smime_docs/linux.html returns 404 Not Found.
* **What are the relevant issue numbers?**
#530

### CODE REVIEW

**Comment by toogley** [comment]
@neomutt/reviewers please review.

**Comment by l2dy** [comment]
`-certfile` was supposed to point to intermediates (https://github.com/neomutt/neomutt/blob/neomutt-20170428/smime.c#L54) but in smime_keys_test.pl the client certificate is directly signed by the CA and no intermediates exists. I kept `-certfile` to test the functionality but the right way is to remove it.

Also `%i` is not documented in https://github.com/neomutt/neomutt/blob/neomutt-20170428/init.h#L3364.

**Comment by toogley** [comment]
@l2dy Could you please move the content of smime-notes.txt into the [manual](https://github.com/neomutt/neomutt/blob/master/doc/manual.xml.head) The basic idea of #530 is to integrate documentation files which are not related to the manual, the manpages or the website into the manual, some manpage or the website. Sorry, i forgot that to note.

**Comment by l2dy** [comment]
@toogley This PR only intents to remove `contrib/ca-bundle.crt` and its references. I've fixed some S/MIME stuff at convenience but doc changes should be done in another PR.

**Comment by l2dy** [comment]
Has anyone checked smime_keys_test.pl with OpenSSL 1.1.0 or other OS?

**Comment by l2dy** [comment]
Alternative links for certificate export in Firefox:
* http://www.hoylen.com/articles/it/email/security/firefox.html
* https://eca.orc.com/wp-content/uploads/ECA_Docs/Firefox_Instructions/BackUp_cert_Firefox.pdf
* https://support.comodo.com/index.php?/Knowledgebase/Article/View/655/23/how-do-i-backup-my-certificate-with-firefox (incorrectly instructs to click "Backup All")

**Comment by flatcap** [comment]
Whilst watching a bit of TV, I went through all the expandos and found three other missing options.
I've added a commit to the set.

Thanks.  Merged.

**Pull request merged**
