### PR TITLE
Use gmtime_r and localtime_r

### PR DESCRIPTION
**Pull request by flatcap**
Use `gmtime_r()` and `localtime_r()`, rather than their non-thread-safe versions.

### CODE REVIEW

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging 7c5c39659f3c5ace83be3b337fdcc512243bf950 into d2e9dcafe36ab8a602474d4c725a070a72159956 - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-3019d7d3445a5f123ab127d5e4e8832752d1bc9e)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
@gahr 
The functions are in [POSIX:2001](http://pubs.opengroup.org/onlinepubs/009695399/functions/gmtime.html) (in an optional section: "Thread-Safe Functions").
Do you think I should get `auto.def` to check for `gmtime_r()`?
If so, I'll refactor all the calls into a library function.

**Comment by gahr** [comment]
I would be surprised by an implementation providing gmtime but not gmtime_r... I'd say let's use it and handle fallout in case..

**Comment by gahr** [comment]
I would perhaps wrap it anyway into a `struct tm mutt_gmtime(void)` function to simplify use (avoid having to first create a `struct tm` on the stack then pass it by pointer).

**Comment by flatcap** [comment]
> implementation providing gmtime but not gmtime_r

Being thread-related, I wondered about Cygwin.

> perhaps wrap it anyway

Yeah, will do.

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging 7706112dc1af464b0b5f0266f9c556cb7a057b7e into 69f8d0f253879a2770be24222a562fc29f1893ac - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-a44d1118df9c1cedb62a01cdd2d5efd825059420)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging d80bb7fe8acdcd0dbc66ca55a4c0caf47d51998c into 69f8d0f253879a2770be24222a562fc29f1893ac - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-ae56a4c587feba104c3dd23e3d7e7c328a95de46)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging e08d8621fe677d3a69c7a11d241e0aeba238e9d2 into 69f8d0f253879a2770be24222a562fc29f1893ac - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-e33cfb7ebd2c244ffe259200050a006472c6f78d)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging 814422671846c3391c0293eee7a77221c696c216 into 44014f68536ba522ce2d883ffcfc76db29b2b0db - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-1fd81b97148c15aa3b74d3e98c1b14ab3705b28c)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging f3e12cf00e1f7885ad65095bfcd00f58d0c74102 into 9bc1e167ebb110fd83d6e5558e2943323192d3f9 - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-4ab918ae890e3bdbc8e04da10b75ee89337d0fb2)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging b69c24f9f725146b0eb13b5064232ddd1d203cd5 into 00a844b9d0b450d92eab501506d7bc17c7f4853d - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-d4c45a390744ae854670b705316642e8768534a3)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging cb62350c8b9f500ee29bb12363830f2536a3a5d8 into d3ad29052a8bfb10bbe122eba823c38b74ca47d1 - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-ab1f8f56e18bbb7ae9849264934c406dc975c9c7)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
This pull request **fixes 5 alerts** when merging f7931f8493115d172f36429b97c95975043b239c into 11488feb1de8022aa50e988d062155560c1be4c6 - [view on LGTM.com](https://lgtm.com/projects/g/neomutt/neomutt/rev/pr-d8a81110b9e14261396852b21067811b351cb9d3)

**fixed alerts:**

* 5 for Use of potentially dangerous function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by flatcap** [comment]
This PR has been superseded by @ghikio's work in branch [[devel/time](https://github.com/neomutt/neomutt/tree/devel/time)].

**Pull request closed without merging**
