### PR TITLE
Update zh_CN translation

### PR DESCRIPTION
**Pull request by l2dy**
* **What does this PR do?**
Fix some Chinese (Simplified) translation.

* **Are there points in the code the reviewer needs to double check?**
@flatcap Should translation PRs be made on the translate branch?

* **Screenshots (if relevant)**

* **Does this PR meet the acceptance criteria?** (This is just a reminder for you,
  this section can be removed if you fulfill it.)

   - Documentation created/updated (you have to edit
     [doc/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/master/doc/manual.xml.head)
     for that)

   - All builds are passing

   - Added [doxygen code documentation](https://neomutt.org/dev/doxygen)
     [syntax](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)

   - Code follows the [style guide](https://neomutt.org/dev/coding-style)

* **What are the relevant issue numbers?**

### CODE REVIEW

**Comment by l2dy** [comment]
PR builds shouldn't attempt deploy to website.

**Comment by yuzibo** [comment]
Hello,
１.
"Decode-save tagged to mailbox"
"解码保存到信箱" 是否为"被标记的解码保存到信箱"更好一些？　：）
２.
Maybe dropping the "fuzzy" string to update translate page:
https://neomutt.org/translate

**Comment by l2dy** [comment]
1. I was using Poedit and it didn't show me the plural source string... I'll leave it alone since I don't know how to handle plural translation.
2. I'm keeing `fuzzy` unless I'm sure it's translated correctly.

**Comment by yuzibo** [comment]
Hi,
1. The plural string does not effect Chinese translate.
In po/zh_CN.po head section, here is 
```bash
...
Language-Team: i18n-zh <i18n-zh@googlegroups.com>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
```
I think Chinese version is "nplurals=1"
2. You are right.But after Rich merging,you have to commit again.

**Comment by l2dy** [comment]
Problem is this isn't about plural words. The singular msgid doesn't involve tagging but the plural one does.

```
msgid "Decode-save to mailbox"
msgid_plural "Decode-save tagged to mailbox"

msgid "Decrypt-save to mailbox"
msgid_plural "Decrypt-save tagged to mailbox"
```

**Comment by yuzibo** [comment]
Maybe you can refer to ga.po to modify the "Plural-forms" :)

**Comment by l2dy** [comment]
>In Poedit, I see [...]

Yes, I noticed that later and edited my comment.

Poedit formats the .po file every time I save it, so I'm committing the formatting change in a944a159043df29b9360dff1853216b06e5844ba. I can discard this commit if anyone objects it, but it will be difficult to contribute with Poedit unless Poedit can be configured to preserve the original formatting.

**Comment by l2dy** [comment]
Can I merge this pull request now?

**Comment by flatcap** [comment]
I've:
- merged all your changes
- reverted the bogus plurals
- changed the build to prevent unnecessary wrapping

@l2dy 
Now that the strings are unwrapped, you'll need to turn off wrapping in Poedit (Edit, Preferences, Advanced).
All the other changes were valid (and would have happened when I sync'd the translations)

**Comment by l2dy** [comment]
@flatcap

Thanks. Should I always make pull requests or directly push to the translate branch?

**Comment by flatcap** [comment]
@l2dy 
Replied on the Translator Team discussion board: https://github.com/orgs/neomutt/teams/translators/discussions/8

**Comment by reisradomil** [comment]
> @reisradomil Do you have time to undo those two uses of ngettext()?

@flatcap Sorry for being late to the party. As I see you reverted that change yourself.
After reverting we now have this:
```
if (h)
  mutt_str_strfcpy(prompt, _("Bounce message to: "), sizeof(prompt));
else
  mutt_str_strfcpy(prompt, _("Bounce tagged messages to: "), sizeof(prompt));
````
Would it be worth to have something like
```
if (h)
  mutt_str_strfcpy(prompt, _("Bounce message to: "), sizeof(prompt));
else
  mutt_str_strfcpy(prompt, ngettext("Bounce tagged message to", "Bounce tagged messages to: ", msgcount), sizeof(prompt));
````
i.e. formulate the question according to the actual number of tagged messages? Or should we stay with the "generic plural" phrase?

**Comment by flatcap** [comment]
@reisradomil 

> Sorry for being late to the party

No worries.

> As I see you reverted that change yourself.

Yes, I was fixing a bunch of other things, anyway.
I was keen to give the translators as much time as possible before the release.

> Would it be worth to have something like...
> i.e. formulate the question according to the actual number of tagged messages?
> Or should we stay with the "generic plural" phrase?

Hmm... interesting.
The number of tagged messages will most likely be plural.
Perhaps for the singular-tagged-case, we should use the singular-non-tagged message.
Perhaps that's more confusing.

Leave it for now.

Thanks.

**Pull request merged**
